// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/m13ha/asiko/models/entities"
	mock "github.com/stretchr/testify/mock"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

// SendBookingCancellation provides a mock function with given fields: booking
func (_m *NotificationService) SendBookingCancellation(booking *entities.Booking) error {
	ret := _m.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for SendBookingCancellation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Booking) error); ok {
		r0 = rf(booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendBookingConfirmation provides a mock function with given fields: booking
func (_m *NotificationService) SendBookingConfirmation(booking *entities.Booking) error {
	ret := _m.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for SendBookingConfirmation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Booking) error); ok {
		r0 = rf(booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendBookingRejection provides a mock function with given fields: booking
func (_m *NotificationService) SendBookingRejection(booking *entities.Booking) error {
	ret := _m.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for SendBookingRejection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Booking) error); ok {
		r0 = rf(booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendVerificationCode provides a mock function with given fields: email, code
func (_m *NotificationService) SendVerificationCode(email string, code string) error {
	ret := _m.Called(email, code)

	if len(ret) == 0 {
		panic("no return value specified for SendVerificationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
