// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mail "github.com/sendgrid/sendgrid-go/helpers/mail"
	mock "github.com/stretchr/testify/mock"

	rest "github.com/sendgrid/rest"
)

// sgSender is an autogenerated mock type for the sgSender type
type sgSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: _a0
func (_m *sgSender) Send(_a0 *mail.SGMailV3) (*rest.Response, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 *rest.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*mail.SGMailV3) (*rest.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*mail.SGMailV3) *rest.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*mail.SGMailV3) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newSgSender creates a new instance of sgSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSgSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *sgSender {
	mock := &sgSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
