/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorsApiErrorResponse,
  RequestsLoginRequest,
  RequestsUserRequest,
  ResponsesLoginResponse,
  ResponsesSimpleMessageResponse,
  ResponsesUserResponse,
} from '../models/index';
import {
    ErrorsApiErrorResponseFromJSON,
    ErrorsApiErrorResponseToJSON,
    RequestsLoginRequestFromJSON,
    RequestsLoginRequestToJSON,
    RequestsUserRequestFromJSON,
    RequestsUserRequestToJSON,
    ResponsesLoginResponseFromJSON,
    ResponsesLoginResponseToJSON,
    ResponsesSimpleMessageResponseFromJSON,
    ResponsesSimpleMessageResponseToJSON,
    ResponsesUserResponseFromJSON,
    ResponsesUserResponseToJSON,
} from '../models/index';

export interface CreateUserRequest {
    user: RequestsUserRequest;
}

export interface LoginUserRequest {
    login: RequestsLoginRequest;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Register a new user in the system.
     * Create a new user
     */
    async createUserRaw(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponsesUserResponse>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling createUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestsUserRequestToJSON(requestParameters['user']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesUserResponseFromJSON(jsonValue));
    }

    /**
     * Register a new user in the system.
     * Create a new user
     */
    async createUser(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponsesUserResponse> {
        const response = await this.createUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Authenticate a user and receive a JWT token.
     * User Login
     */
    async loginUserRaw(requestParameters: LoginUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponsesLoginResponse>> {
        if (requestParameters['login'] == null) {
            throw new runtime.RequiredError(
                'login',
                'Required parameter "login" was null or undefined when calling loginUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestsLoginRequestToJSON(requestParameters['login']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesLoginResponseFromJSON(jsonValue));
    }

    /**
     * Authenticate a user and receive a JWT token.
     * User Login
     */
    async loginUser(requestParameters: LoginUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponsesLoginResponse> {
        const response = await this.loginUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Invalidate the user\'s session.
     * User Logout
     */
    async logoutUserRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponsesSimpleMessageResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesSimpleMessageResponseFromJSON(jsonValue));
    }

    /**
     * Invalidate the user\'s session.
     * User Logout
     */
    async logoutUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponsesSimpleMessageResponse> {
        const response = await this.logoutUserRaw(initOverrides);
        return await response.value();
    }

}
