// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	entities "github.com/m13ha/appointment_master/models/entities"

	mock "github.com/stretchr/testify/mock"

	paginate "github.com/morkid/paginate"

	requests "github.com/m13ha/appointment_master/models/requests"

	uuid "github.com/google/uuid"
)

// AppointmentService is an autogenerated mock type for the AppointmentService type
type AppointmentService struct {
	mock.Mock
}

type AppointmentService_Expecter struct {
	mock *mock.Mock
}

func (_m *AppointmentService) EXPECT() *AppointmentService_Expecter {
	return &AppointmentService_Expecter{mock: &_m.Mock}
}

// CreateAppointment provides a mock function with given fields: req, userId
func (_m *AppointmentService) CreateAppointment(req requests.AppointmentRequest, userId uuid.UUID) (*entities.Appointment, error) {
	ret := _m.Called(req, userId)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppointment")
	}

	var r0 *entities.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.AppointmentRequest, uuid.UUID) (*entities.Appointment, error)); ok {
		return rf(req, userId)
	}
	if rf, ok := ret.Get(0).(func(requests.AppointmentRequest, uuid.UUID) *entities.Appointment); ok {
		r0 = rf(req, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.AppointmentRequest, uuid.UUID) error); ok {
		r1 = rf(req, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AppointmentService_CreateAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAppointment'
type AppointmentService_CreateAppointment_Call struct {
	*mock.Call
}

// CreateAppointment is a helper method to define mock.On call
//   - req requests.AppointmentRequest
//   - userId uuid.UUID
func (_e *AppointmentService_Expecter) CreateAppointment(req interface{}, userId interface{}) *AppointmentService_CreateAppointment_Call {
	return &AppointmentService_CreateAppointment_Call{Call: _e.mock.On("CreateAppointment", req, userId)}
}

func (_c *AppointmentService_CreateAppointment_Call) Run(run func(req requests.AppointmentRequest, userId uuid.UUID)) *AppointmentService_CreateAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(requests.AppointmentRequest), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AppointmentService_CreateAppointment_Call) Return(_a0 *entities.Appointment, _a1 error) *AppointmentService_CreateAppointment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AppointmentService_CreateAppointment_Call) RunAndReturn(run func(requests.AppointmentRequest, uuid.UUID) (*entities.Appointment, error)) *AppointmentService_CreateAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAppointmentsCreatedByUser provides a mock function with given fields: userID, r
func (_m *AppointmentService) GetAllAppointmentsCreatedByUser(userID string, r *http.Request) paginate.Page {
	ret := _m.Called(userID, r)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAppointmentsCreatedByUser")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(string, *http.Request) paginate.Page); ok {
		r0 = rf(userID, r)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// AppointmentService_GetAllAppointmentsCreatedByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAppointmentsCreatedByUser'
type AppointmentService_GetAllAppointmentsCreatedByUser_Call struct {
	*mock.Call
}

// GetAllAppointmentsCreatedByUser is a helper method to define mock.On call
//   - userID string
//   - r *http.Request
func (_e *AppointmentService_Expecter) GetAllAppointmentsCreatedByUser(userID interface{}, r interface{}) *AppointmentService_GetAllAppointmentsCreatedByUser_Call {
	return &AppointmentService_GetAllAppointmentsCreatedByUser_Call{Call: _e.mock.On("GetAllAppointmentsCreatedByUser", userID, r)}
}

func (_c *AppointmentService_GetAllAppointmentsCreatedByUser_Call) Run(run func(userID string, r *http.Request)) *AppointmentService_GetAllAppointmentsCreatedByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*http.Request))
	})
	return _c
}

func (_c *AppointmentService_GetAllAppointmentsCreatedByUser_Call) Return(_a0 paginate.Page) *AppointmentService_GetAllAppointmentsCreatedByUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppointmentService_GetAllAppointmentsCreatedByUser_Call) RunAndReturn(run func(string, *http.Request) paginate.Page) *AppointmentService_GetAllAppointmentsCreatedByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewAppointmentService creates a new instance of AppointmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppointmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppointmentService {
	mock := &AppointmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
