// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/m13ha/appointment_master/models/entities"
	mock "github.com/stretchr/testify/mock"

	paginate "github.com/morkid/paginate"

	requests "github.com/m13ha/appointment_master/models/requests"
)

// BookingService is an autogenerated mock type for the BookingService type
type BookingService struct {
	mock.Mock
}

type BookingService_Expecter struct {
	mock *mock.Mock
}

func (_m *BookingService) EXPECT() *BookingService_Expecter {
	return &BookingService_Expecter{mock: &_m.Mock}
}

// BookAppointment provides a mock function with given fields: req, userIDStr
func (_m *BookingService) BookAppointment(req requests.BookingRequest, userIDStr string) (*entities.Booking, error) {
	ret := _m.Called(req, userIDStr)

	if len(ret) == 0 {
		panic("no return value specified for BookAppointment")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.BookingRequest, string) (*entities.Booking, error)); ok {
		return rf(req, userIDStr)
	}
	if rf, ok := ret.Get(0).(func(requests.BookingRequest, string) *entities.Booking); ok {
		r0 = rf(req, userIDStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.BookingRequest, string) error); ok {
		r1 = rf(req, userIDStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingService_BookAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BookAppointment'
type BookingService_BookAppointment_Call struct {
	*mock.Call
}

// BookAppointment is a helper method to define mock.On call
//   - req requests.BookingRequest
//   - userIDStr string
func (_e *BookingService_Expecter) BookAppointment(req interface{}, userIDStr interface{}) *BookingService_BookAppointment_Call {
	return &BookingService_BookAppointment_Call{Call: _e.mock.On("BookAppointment", req, userIDStr)}
}

func (_c *BookingService_BookAppointment_Call) Run(run func(req requests.BookingRequest, userIDStr string)) *BookingService_BookAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(requests.BookingRequest), args[1].(string))
	})
	return _c
}

func (_c *BookingService_BookAppointment_Call) Return(_a0 *entities.Booking, _a1 error) *BookingService_BookAppointment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingService_BookAppointment_Call) RunAndReturn(run func(requests.BookingRequest, string) (*entities.Booking, error)) *BookingService_BookAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// BookGuestAppointment provides a mock function with given fields: req
func (_m *BookingService) BookGuestAppointment(req requests.BookingRequest) (*entities.Booking, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for BookGuestAppointment")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.BookingRequest) (*entities.Booking, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(requests.BookingRequest) *entities.Booking); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.BookingRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingService_BookGuestAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BookGuestAppointment'
type BookingService_BookGuestAppointment_Call struct {
	*mock.Call
}

// BookGuestAppointment is a helper method to define mock.On call
//   - req requests.BookingRequest
func (_e *BookingService_Expecter) BookGuestAppointment(req interface{}) *BookingService_BookGuestAppointment_Call {
	return &BookingService_BookGuestAppointment_Call{Call: _e.mock.On("BookGuestAppointment", req)}
}

func (_c *BookingService_BookGuestAppointment_Call) Run(run func(req requests.BookingRequest)) *BookingService_BookGuestAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(requests.BookingRequest))
	})
	return _c
}

func (_c *BookingService_BookGuestAppointment_Call) Return(_a0 *entities.Booking, _a1 error) *BookingService_BookGuestAppointment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingService_BookGuestAppointment_Call) RunAndReturn(run func(requests.BookingRequest) (*entities.Booking, error)) *BookingService_BookGuestAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// BookRegisteredUserAppointment provides a mock function with given fields: req, userIDStr
func (_m *BookingService) BookRegisteredUserAppointment(req requests.BookingRequest, userIDStr string) (*entities.Booking, error) {
	ret := _m.Called(req, userIDStr)

	if len(ret) == 0 {
		panic("no return value specified for BookRegisteredUserAppointment")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.BookingRequest, string) (*entities.Booking, error)); ok {
		return rf(req, userIDStr)
	}
	if rf, ok := ret.Get(0).(func(requests.BookingRequest, string) *entities.Booking); ok {
		r0 = rf(req, userIDStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.BookingRequest, string) error); ok {
		r1 = rf(req, userIDStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingService_BookRegisteredUserAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BookRegisteredUserAppointment'
type BookingService_BookRegisteredUserAppointment_Call struct {
	*mock.Call
}

// BookRegisteredUserAppointment is a helper method to define mock.On call
//   - req requests.BookingRequest
//   - userIDStr string
func (_e *BookingService_Expecter) BookRegisteredUserAppointment(req interface{}, userIDStr interface{}) *BookingService_BookRegisteredUserAppointment_Call {
	return &BookingService_BookRegisteredUserAppointment_Call{Call: _e.mock.On("BookRegisteredUserAppointment", req, userIDStr)}
}

func (_c *BookingService_BookRegisteredUserAppointment_Call) Run(run func(req requests.BookingRequest, userIDStr string)) *BookingService_BookRegisteredUserAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(requests.BookingRequest), args[1].(string))
	})
	return _c
}

func (_c *BookingService_BookRegisteredUserAppointment_Call) Return(_a0 *entities.Booking, _a1 error) *BookingService_BookRegisteredUserAppointment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingService_BookRegisteredUserAppointment_Call) RunAndReturn(run func(requests.BookingRequest, string) (*entities.Booking, error)) *BookingService_BookRegisteredUserAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// CancelBookingByCode provides a mock function with given fields: bookingCode
func (_m *BookingService) CancelBookingByCode(bookingCode string) (*entities.Booking, error) {
	ret := _m.Called(bookingCode)

	if len(ret) == 0 {
		panic("no return value specified for CancelBookingByCode")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Booking, error)); ok {
		return rf(bookingCode)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Booking); ok {
		r0 = rf(bookingCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bookingCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingService_CancelBookingByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelBookingByCode'
type BookingService_CancelBookingByCode_Call struct {
	*mock.Call
}

// CancelBookingByCode is a helper method to define mock.On call
//   - bookingCode string
func (_e *BookingService_Expecter) CancelBookingByCode(bookingCode interface{}) *BookingService_CancelBookingByCode_Call {
	return &BookingService_CancelBookingByCode_Call{Call: _e.mock.On("CancelBookingByCode", bookingCode)}
}

func (_c *BookingService_CancelBookingByCode_Call) Run(run func(bookingCode string)) *BookingService_CancelBookingByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *BookingService_CancelBookingByCode_Call) Return(_a0 *entities.Booking, _a1 error) *BookingService_CancelBookingByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingService_CancelBookingByCode_Call) RunAndReturn(run func(string) (*entities.Booking, error)) *BookingService_CancelBookingByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBookingsForAppointment provides a mock function with given fields: ctx, appcode
func (_m *BookingService) GetAllBookingsForAppointment(ctx context.Context, appcode string) (paginate.Page, error) {
	ret := _m.Called(ctx, appcode)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBookingsForAppointment")
	}

	var r0 paginate.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (paginate.Page, error)); ok {
		return rf(ctx, appcode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) paginate.Page); ok {
		r0 = rf(ctx, appcode)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, appcode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingService_GetAllBookingsForAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBookingsForAppointment'
type BookingService_GetAllBookingsForAppointment_Call struct {
	*mock.Call
}

// GetAllBookingsForAppointment is a helper method to define mock.On call
//   - ctx context.Context
//   - appcode string
func (_e *BookingService_Expecter) GetAllBookingsForAppointment(ctx interface{}, appcode interface{}) *BookingService_GetAllBookingsForAppointment_Call {
	return &BookingService_GetAllBookingsForAppointment_Call{Call: _e.mock.On("GetAllBookingsForAppointment", ctx, appcode)}
}

func (_c *BookingService_GetAllBookingsForAppointment_Call) Run(run func(ctx context.Context, appcode string)) *BookingService_GetAllBookingsForAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BookingService_GetAllBookingsForAppointment_Call) Return(_a0 paginate.Page, _a1 error) *BookingService_GetAllBookingsForAppointment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingService_GetAllBookingsForAppointment_Call) RunAndReturn(run func(context.Context, string) (paginate.Page, error)) *BookingService_GetAllBookingsForAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailableSlots provides a mock function with given fields: ctx, appcode
func (_m *BookingService) GetAvailableSlots(ctx context.Context, appcode string) (paginate.Page, error) {
	ret := _m.Called(ctx, appcode)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSlots")
	}

	var r0 paginate.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (paginate.Page, error)); ok {
		return rf(ctx, appcode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) paginate.Page); ok {
		r0 = rf(ctx, appcode)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, appcode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingService_GetAvailableSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableSlots'
type BookingService_GetAvailableSlots_Call struct {
	*mock.Call
}

// GetAvailableSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - appcode string
func (_e *BookingService_Expecter) GetAvailableSlots(ctx interface{}, appcode interface{}) *BookingService_GetAvailableSlots_Call {
	return &BookingService_GetAvailableSlots_Call{Call: _e.mock.On("GetAvailableSlots", ctx, appcode)}
}

func (_c *BookingService_GetAvailableSlots_Call) Run(run func(ctx context.Context, appcode string)) *BookingService_GetAvailableSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BookingService_GetAvailableSlots_Call) Return(_a0 paginate.Page, _a1 error) *BookingService_GetAvailableSlots_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingService_GetAvailableSlots_Call) RunAndReturn(run func(context.Context, string) (paginate.Page, error)) *BookingService_GetAvailableSlots_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailableSlotsByDay provides a mock function with given fields: ctx, appcode, dateStr
func (_m *BookingService) GetAvailableSlotsByDay(ctx context.Context, appcode string, dateStr string) (paginate.Page, error) {
	ret := _m.Called(ctx, appcode, dateStr)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSlotsByDay")
	}

	var r0 paginate.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (paginate.Page, error)); ok {
		return rf(ctx, appcode, dateStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) paginate.Page); ok {
		r0 = rf(ctx, appcode, dateStr)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, appcode, dateStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingService_GetAvailableSlotsByDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableSlotsByDay'
type BookingService_GetAvailableSlotsByDay_Call struct {
	*mock.Call
}

// GetAvailableSlotsByDay is a helper method to define mock.On call
//   - ctx context.Context
//   - appcode string
//   - dateStr string
func (_e *BookingService_Expecter) GetAvailableSlotsByDay(ctx interface{}, appcode interface{}, dateStr interface{}) *BookingService_GetAvailableSlotsByDay_Call {
	return &BookingService_GetAvailableSlotsByDay_Call{Call: _e.mock.On("GetAvailableSlotsByDay", ctx, appcode, dateStr)}
}

func (_c *BookingService_GetAvailableSlotsByDay_Call) Run(run func(ctx context.Context, appcode string, dateStr string)) *BookingService_GetAvailableSlotsByDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *BookingService_GetAvailableSlotsByDay_Call) Return(_a0 paginate.Page, _a1 error) *BookingService_GetAvailableSlotsByDay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingService_GetAvailableSlotsByDay_Call) RunAndReturn(run func(context.Context, string, string) (paginate.Page, error)) *BookingService_GetAvailableSlotsByDay_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingByCode provides a mock function with given fields: bookingCode
func (_m *BookingService) GetBookingByCode(bookingCode string) (*entities.Booking, error) {
	ret := _m.Called(bookingCode)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByCode")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Booking, error)); ok {
		return rf(bookingCode)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Booking); ok {
		r0 = rf(bookingCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bookingCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingService_GetBookingByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingByCode'
type BookingService_GetBookingByCode_Call struct {
	*mock.Call
}

// GetBookingByCode is a helper method to define mock.On call
//   - bookingCode string
func (_e *BookingService_Expecter) GetBookingByCode(bookingCode interface{}) *BookingService_GetBookingByCode_Call {
	return &BookingService_GetBookingByCode_Call{Call: _e.mock.On("GetBookingByCode", bookingCode)}
}

func (_c *BookingService_GetBookingByCode_Call) Run(run func(bookingCode string)) *BookingService_GetBookingByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *BookingService_GetBookingByCode_Call) Return(_a0 *entities.Booking, _a1 error) *BookingService_GetBookingByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingService_GetBookingByCode_Call) RunAndReturn(run func(string) (*entities.Booking, error)) *BookingService_GetBookingByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBookings provides a mock function with given fields: ctx, userID
func (_m *BookingService) GetUserBookings(ctx context.Context, userID string) (paginate.Page, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBookings")
	}

	var r0 paginate.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (paginate.Page, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) paginate.Page); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingService_GetUserBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBookings'
type BookingService_GetUserBookings_Call struct {
	*mock.Call
}

// GetUserBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *BookingService_Expecter) GetUserBookings(ctx interface{}, userID interface{}) *BookingService_GetUserBookings_Call {
	return &BookingService_GetUserBookings_Call{Call: _e.mock.On("GetUserBookings", ctx, userID)}
}

func (_c *BookingService_GetUserBookings_Call) Run(run func(ctx context.Context, userID string)) *BookingService_GetUserBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BookingService_GetUserBookings_Call) Return(_a0 paginate.Page, _a1 error) *BookingService_GetUserBookings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingService_GetUserBookings_Call) RunAndReturn(run func(context.Context, string) (paginate.Page, error)) *BookingService_GetUserBookings_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBookingByCode provides a mock function with given fields: bookingCode, req
func (_m *BookingService) UpdateBookingByCode(bookingCode string, req requests.BookingRequest) (*entities.Booking, error) {
	ret := _m.Called(bookingCode, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookingByCode")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string, requests.BookingRequest) (*entities.Booking, error)); ok {
		return rf(bookingCode, req)
	}
	if rf, ok := ret.Get(0).(func(string, requests.BookingRequest) *entities.Booking); ok {
		r0 = rf(bookingCode, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string, requests.BookingRequest) error); ok {
		r1 = rf(bookingCode, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingService_UpdateBookingByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBookingByCode'
type BookingService_UpdateBookingByCode_Call struct {
	*mock.Call
}

// UpdateBookingByCode is a helper method to define mock.On call
//   - bookingCode string
//   - req requests.BookingRequest
func (_e *BookingService_Expecter) UpdateBookingByCode(bookingCode interface{}, req interface{}) *BookingService_UpdateBookingByCode_Call {
	return &BookingService_UpdateBookingByCode_Call{Call: _e.mock.On("UpdateBookingByCode", bookingCode, req)}
}

func (_c *BookingService_UpdateBookingByCode_Call) Run(run func(bookingCode string, req requests.BookingRequest)) *BookingService_UpdateBookingByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(requests.BookingRequest))
	})
	return _c
}

func (_c *BookingService_UpdateBookingByCode_Call) Return(_a0 *entities.Booking, _a1 error) *BookingService_UpdateBookingByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingService_UpdateBookingByCode_Call) RunAndReturn(run func(string, requests.BookingRequest) (*entities.Booking, error)) *BookingService_UpdateBookingByCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewBookingService creates a new instance of BookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingService {
	mock := &BookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
