// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/m13ha/appointment_master/models/entities"
	mock "github.com/stretchr/testify/mock"

	requests "github.com/m13ha/appointment_master/models/requests"

	responses "github.com/m13ha/appointment_master/models/responses"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// AuthenticateUser provides a mock function with given fields: email, password
func (_m *UserService) AuthenticateUser(email string, password string) (*entities.User, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*entities.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *entities.User); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_AuthenticateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateUser'
type UserService_AuthenticateUser_Call struct {
	*mock.Call
}

// AuthenticateUser is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *UserService_Expecter) AuthenticateUser(email interface{}, password interface{}) *UserService_AuthenticateUser_Call {
	return &UserService_AuthenticateUser_Call{Call: _e.mock.On("AuthenticateUser", email, password)}
}

func (_c *UserService_AuthenticateUser_Call) Run(run func(email string, password string)) *UserService_AuthenticateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *UserService_AuthenticateUser_Call) Return(_a0 *entities.User, _a1 error) *UserService_AuthenticateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_AuthenticateUser_Call) RunAndReturn(run func(string, string) (*entities.User, error)) *UserService_AuthenticateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: userReq
func (_m *UserService) CreateUser(userReq requests.UserRequest) (*responses.UserResponse, error) {
	ret := _m.Called(userReq)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *responses.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.UserRequest) (*responses.UserResponse, error)); ok {
		return rf(userReq)
	}
	if rf, ok := ret.Get(0).(func(requests.UserRequest) *responses.UserResponse); ok {
		r0 = rf(userReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.UserRequest) error); ok {
		r1 = rf(userReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - userReq requests.UserRequest
func (_e *UserService_Expecter) CreateUser(userReq interface{}) *UserService_CreateUser_Call {
	return &UserService_CreateUser_Call{Call: _e.mock.On("CreateUser", userReq)}
}

func (_c *UserService_CreateUser_Call) Run(run func(userReq requests.UserRequest)) *UserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(requests.UserRequest))
	})
	return _c
}

func (_c *UserService_CreateUser_Call) Return(_a0 *responses.UserResponse, _a1 error) *UserService_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_CreateUser_Call) RunAndReturn(run func(requests.UserRequest) (*responses.UserResponse, error)) *UserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
