// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	"github.com/m13ha/appointment_master/models/entities"
	"github.com/m13ha/appointment_master/models/requests"
	"github.com/morkid/paginate"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AppointmentService is an autogenerated mock type for the AppointmentService type
type AppointmentService struct {
	mock.Mock
}

// CreateAppointment provides a mock function with given fields: req, userId
func (_m *AppointmentService) CreateAppointment(req requests.AppointmentRequest, userId uuid.UUID) (*entities.Appointment, error) {
	ret := _m.Called(req, userId)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppointment")
	}

	var r0 *entities.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.AppointmentRequest, uuid.UUID) (*entities.Appointment, error)); ok {
		return rf(req, userId)
	}
	if rf, ok := ret.Get(0).(func(requests.AppointmentRequest, uuid.UUID) *entities.Appointment); ok {
		r0 = rf(req, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.AppointmentRequest, uuid.UUID) error); ok {
		r1 = rf(req, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllAppointmentsCreatedByUser provides a mock function with given fields: userID, r
func (_m *AppointmentService) GetAllAppointmentsCreatedByUser(userID string, r *http.Request) paginate.Page {
	ret := _m.Called(userID, r)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAppointmentsCreatedByUser")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(string, *http.Request) paginate.Page); ok {
		r0 = rf(userID, r)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// NewAppointmentService creates a new instance of AppointmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppointmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppointmentService {
	mock := &AppointmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
