// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	entities "github.com/m13ha/asiko/models/entities"

	mock "github.com/stretchr/testify/mock"

	paginate "github.com/morkid/paginate"

	requests "github.com/m13ha/asiko/models/requests"

	services "github.com/m13ha/asiko/services"

	time "time"

	uuid "github.com/google/uuid"
)

// AppointmentService is an autogenerated mock type for the AppointmentService type
type AppointmentService struct {
	mock.Mock
}

// CancelAppointment provides a mock function with given fields: ctx, appointmentID, ownerID
func (_m *AppointmentService) CancelAppointment(ctx context.Context, appointmentID uuid.UUID, ownerID uuid.UUID) (*entities.Appointment, error) {
	ret := _m.Called(ctx, appointmentID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for CancelAppointment")
	}

	var r0 *entities.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entities.Appointment, error)); ok {
		return rf(ctx, appointmentID, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entities.Appointment); ok {
		r0 = rf(ctx, appointmentID, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, appointmentID, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateAppointment provides a mock function with given fields: req, userId
func (_m *AppointmentService) CreateAppointment(req requests.AppointmentRequest, userId uuid.UUID) (*entities.Appointment, error) {
	ret := _m.Called(req, userId)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppointment")
	}

	var r0 *entities.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.AppointmentRequest, uuid.UUID) (*entities.Appointment, error)); ok {
		return rf(req, userId)
	}
	if rf, ok := ret.Get(0).(func(requests.AppointmentRequest, uuid.UUID) *entities.Appointment); ok {
		r0 = rf(req, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.AppointmentRequest, uuid.UUID) error); ok {
		r1 = rf(req, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllAppointmentsCreatedByUser provides a mock function with given fields: userID, r, statuses
func (_m *AppointmentService) GetAllAppointmentsCreatedByUser(userID string, r *http.Request, statuses []entities.AppointmentStatus) paginate.Page {
	ret := _m.Called(userID, r, statuses)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAppointmentsCreatedByUser")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(string, *http.Request, []entities.AppointmentStatus) paginate.Page); ok {
		r0 = rf(userID, r, statuses)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// RefreshStatuses provides a mock function with given fields: ctx, now
func (_m *AppointmentService) RefreshStatuses(ctx context.Context, now time.Time) (services.StatusRefreshSummary, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for RefreshStatuses")
	}

	var r0 services.StatusRefreshSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (services.StatusRefreshSummary, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) services.StatusRefreshSummary); ok {
		r0 = rf(ctx, now)
	} else {
		r0 = ret.Get(0).(services.StatusRefreshSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAppointmentService creates a new instance of AppointmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppointmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppointmentService {
	mock := &AppointmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
