// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AppointmentStatusScheduler is an autogenerated mock type for the AppointmentStatusScheduler type
type AppointmentStatusScheduler struct {
	mock.Mock
}

// Start provides a mock function with given fields: ctx
func (_m *AppointmentStatusScheduler) Start(ctx context.Context) {
	_m.Called(ctx)
}

// NewAppointmentStatusScheduler creates a new instance of AppointmentStatusScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppointmentStatusScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppointmentStatusScheduler {
	mock := &AppointmentStatusScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
