// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"github.com/google/uuid"
	"github.com/m13ha/appointment_master/models/entities"
	"github.com/stretchr/testify/mock"
)

// BanListService is an autogenerated mock type for the BanListService type
type BanListService struct {
	mock.Mock
}

// AddToBanList provides a mock function with given fields: userID, email
func (_m *BanListService) AddToBanList(userID uuid.UUID, email string) (*entities.BanListEntry, error) {
	ret := _m.Called(userID, email)

	var r0 *entities.BanListEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (*entities.BanListEntry, error)); ok {
		return rf(userID, email)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) *entities.BanListEntry); ok {
		r0 = rf(userID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.BanListEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(userID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBanList provides a mock function with given fields: userID
func (_m *BanListService) GetBanList(userID uuid.UUID) ([]entities.BanListEntry, error) {
	ret := _m.Called(userID)

	var r0 []entities.BanListEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]entities.BanListEntry, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []entities.BanListEntry); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.BanListEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveFromBanList provides a mock function with given fields: userID, email
func (_m *BanListService) RemoveFromBanList(userID uuid.UUID, email string) error {
	ret := _m.Called(userID, email)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) error); ok {
		r0 = rf(userID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}