// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/m13ha/appointment_master/models/entities"
	mock "github.com/stretchr/testify/mock"

	paginate "github.com/morkid/paginate"

	requests "github.com/m13ha/appointment_master/models/requests"

	uuid "github.com/google/uuid"
)

// BookingService is an autogenerated mock type for the BookingService type
type BookingService struct {
	mock.Mock
}

// BookAppointment provides a mock function with given fields: req, userIDStr
func (_m *BookingService) BookAppointment(req requests.BookingRequest, userIDStr string) (*entities.Booking, error) {
	ret := _m.Called(req, userIDStr)

	if len(ret) == 0 {
		panic("no return value specified for BookAppointment")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.BookingRequest, string) (*entities.Booking, error)); ok {
		return rf(req, userIDStr)
	}
	if rf, ok := ret.Get(0).(func(requests.BookingRequest, string) *entities.Booking); ok {
		r0 = rf(req, userIDStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.BookingRequest, string) error); ok {
		r1 = rf(req, userIDStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookGuestAppointment provides a mock function with given fields: req
func (_m *BookingService) BookGuestAppointment(req requests.BookingRequest) (*entities.Booking, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for BookGuestAppointment")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.BookingRequest) (*entities.Booking, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(requests.BookingRequest) *entities.Booking); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.BookingRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookRegisteredUserAppointment provides a mock function with given fields: req, userIDStr
func (_m *BookingService) BookRegisteredUserAppointment(req requests.BookingRequest, userIDStr string) (*entities.Booking, error) {
	ret := _m.Called(req, userIDStr)

	if len(ret) == 0 {
		panic("no return value specified for BookRegisteredUserAppointment")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.BookingRequest, string) (*entities.Booking, error)); ok {
		return rf(req, userIDStr)
	}
	if rf, ok := ret.Get(0).(func(requests.BookingRequest, string) *entities.Booking); ok {
		r0 = rf(req, userIDStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.BookingRequest, string) error); ok {
		r1 = rf(req, userIDStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelBookingByCode provides a mock function with given fields: bookingCode
func (_m *BookingService) CancelBookingByCode(bookingCode string) (*entities.Booking, error) {
	ret := _m.Called(bookingCode)

	if len(ret) == 0 {
		panic("no return value specified for CancelBookingByCode")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Booking, error)); ok {
		return rf(bookingCode)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Booking); ok {
		r0 = rf(bookingCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bookingCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllBookingsForAppointment provides a mock function with given fields: ctx, appcode
func (_m *BookingService) GetAllBookingsForAppointment(ctx context.Context, appcode string) (paginate.Page, error) {
	ret := _m.Called(ctx, appcode)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBookingsForAppointment")
	}

	var r0 paginate.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (paginate.Page, error)); ok {
		return rf(ctx, appcode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) paginate.Page); ok {
		r0 = rf(ctx, appcode)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, appcode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAvailableSlots provides a mock function with given fields: ctx, appcode
func (_m *BookingService) GetAvailableSlots(ctx context.Context, appcode string) (paginate.Page, error) {
	ret := _m.Called(ctx, appcode)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSlots")
	}

	var r0 paginate.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (paginate.Page, error)); ok {
		return rf(ctx, appcode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) paginate.Page); ok {
		r0 = rf(ctx, appcode)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, appcode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAvailableSlotsByDay provides a mock function with given fields: ctx, appcode, dateStr
func (_m *BookingService) GetAvailableSlotsByDay(ctx context.Context, appcode string, dateStr string) (paginate.Page, error) {
	ret := _m.Called(ctx, appcode, dateStr)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSlotsByDay")
	}

	var r0 paginate.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (paginate.Page, error)); ok {
		return rf(ctx, appcode, dateStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) paginate.Page); ok {
		r0 = rf(ctx, appcode, dateStr)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, appcode, dateStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingByCode provides a mock function with given fields: bookingCode
func (_m *BookingService) GetBookingByCode(bookingCode string) (*entities.Booking, error) {
	ret := _m.Called(bookingCode)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByCode")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Booking, error)); ok {
		return rf(bookingCode)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Booking); ok {
		r0 = rf(bookingCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bookingCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserBookings provides a mock function with given fields: ctx, userID
func (_m *BookingService) GetUserBookings(ctx context.Context, userID string) (paginate.Page, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBookings")
	}

	var r0 paginate.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (paginate.Page, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) paginate.Page); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RejectBooking provides a mock function with given fields: bookingCode, ownerID
func (_m *BookingService) RejectBooking(bookingCode string, ownerID uuid.UUID) (*entities.Booking, error) {
	ret := _m.Called(bookingCode, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for RejectBooking")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID) (*entities.Booking, error)); ok {
		return rf(bookingCode, ownerID)
	}
	if rf, ok := ret.Get(0).(func(string, uuid.UUID) *entities.Booking); ok {
		r0 = rf(bookingCode, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string, uuid.UUID) error); ok {
		r1 = rf(bookingCode, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBookingByCode provides a mock function with given fields: bookingCode, req
func (_m *BookingService) UpdateBookingByCode(bookingCode string, req requests.BookingRequest) (*entities.Booking, error) {
	ret := _m.Called(bookingCode, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookingByCode")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string, requests.BookingRequest) (*entities.Booking, error)); ok {
		return rf(bookingCode, req)
	}
	if rf, ok := ret.Get(0).(func(string, requests.BookingRequest) *entities.Booking); ok {
		r0 = rf(bookingCode, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string, requests.BookingRequest) error); ok {
		r1 = rf(bookingCode, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBookingService creates a new instance of BookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingService {
	mock := &BookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
