// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	paginate "github.com/morkid/paginate"

	uuid "github.com/google/uuid"
)

// EventNotificationService is an autogenerated mock type for the EventNotificationService type
type EventNotificationService struct {
	mock.Mock
}

// CreateEventNotification provides a mock function with given fields: userID, eventType, message, resourceID
func (_m *EventNotificationService) CreateEventNotification(userID uuid.UUID, eventType string, message string, resourceID uuid.UUID) error {
	ret := _m.Called(userID, eventType, message, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for CreateEventNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, uuid.UUID) error); ok {
		r0 = rf(userID, eventType, message, resourceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserNotifications provides a mock function with given fields: ctx, req, userID
func (_m *EventNotificationService) GetUserNotifications(ctx context.Context, req *http.Request, userID string) (paginate.Page, error) {
	ret := _m.Called(ctx, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserNotifications")
	}

	var r0 paginate.Page
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request, string) (paginate.Page, error)); ok {
		return rf(ctx, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request, string) paginate.Page); ok {
		r0 = rf(ctx, req, userID)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *http.Request, string) error); ok {
		r1 = rf(ctx, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAllNotificationsAsRead provides a mock function with given fields: userID
func (_m *EventNotificationService) MarkAllNotificationsAsRead(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllNotificationsAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventNotificationService creates a new instance of EventNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventNotificationService {
	mock := &EventNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
