// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/m13ha/appointment_master/models/entities"
	mock "github.com/stretchr/testify/mock"

	requests "github.com/m13ha/appointment_master/models/requests"

	responses "github.com/m13ha/appointment_master/models/responses"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// AuthenticateUser provides a mock function with given fields: email, password
func (_m *UserService) AuthenticateUser(email string, password string) (*entities.User, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*entities.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *entities.User); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: userReq
func (_m *UserService) CreateUser(userReq requests.UserRequest) (*responses.UserResponse, error) {
	ret := _m.Called(userReq)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *responses.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.UserRequest) (*responses.UserResponse, error)); ok {
		return rf(userReq)
	}
	if rf, ok := ret.Get(0).(func(requests.UserRequest) *responses.UserResponse); ok {
		r0 = rf(userReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.UserRequest) error); ok {
		r1 = rf(userReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyRegistration provides a mock function with given fields: email, code
func (_m *UserService) VerifyRegistration(email string, code string) (string, error) {
	ret := _m.Called(email, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRegistration")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(email, code)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(email, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
