// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/m13ha/appointment_master/models/entities"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	paginate "github.com/morkid/paginate"

	repository "github.com/m13ha/appointment_master/repository"

	uuid "github.com/google/uuid"
)

// AppointmentRepository is an autogenerated mock type for the AppointmentRepository type
type AppointmentRepository struct {
	mock.Mock
}

type AppointmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AppointmentRepository) EXPECT() *AppointmentRepository_Expecter {
	return &AppointmentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: appointment
func (_m *AppointmentRepository) Create(appointment *entities.Appointment) error {
	ret := _m.Called(appointment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Appointment) error); ok {
		r0 = rf(appointment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AppointmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AppointmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - appointment *entities.Appointment
func (_e *AppointmentRepository_Expecter) Create(appointment interface{}) *AppointmentRepository_Create_Call {
	return &AppointmentRepository_Create_Call{Call: _e.mock.On("Create", appointment)}
}

func (_c *AppointmentRepository_Create_Call) Run(run func(appointment *entities.Appointment)) *AppointmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Appointment))
	})
	return _c
}

func (_c *AppointmentRepository_Create_Call) Return(_a0 error) *AppointmentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppointmentRepository_Create_Call) RunAndReturn(run func(*entities.Appointment) error) *AppointmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAndLock provides a mock function with given fields: appCode, tx
func (_m *AppointmentRepository) FindAndLock(appCode string, tx *gorm.DB) (*entities.Appointment, error) {
	ret := _m.Called(appCode, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAndLock")
	}

	var r0 *entities.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *gorm.DB) (*entities.Appointment, error)); ok {
		return rf(appCode, tx)
	}
	if rf, ok := ret.Get(0).(func(string, *gorm.DB) *entities.Appointment); ok {
		r0 = rf(appCode, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *gorm.DB) error); ok {
		r1 = rf(appCode, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AppointmentRepository_FindAndLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAndLock'
type AppointmentRepository_FindAndLock_Call struct {
	*mock.Call
}

// FindAndLock is a helper method to define mock.On call
//   - appCode string
//   - tx *gorm.DB
func (_e *AppointmentRepository_Expecter) FindAndLock(appCode interface{}, tx interface{}) *AppointmentRepository_FindAndLock_Call {
	return &AppointmentRepository_FindAndLock_Call{Call: _e.mock.On("FindAndLock", appCode, tx)}
}

func (_c *AppointmentRepository_FindAndLock_Call) Run(run func(appCode string, tx *gorm.DB)) *AppointmentRepository_FindAndLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*gorm.DB))
	})
	return _c
}

func (_c *AppointmentRepository_FindAndLock_Call) Return(_a0 *entities.Appointment, _a1 error) *AppointmentRepository_FindAndLock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AppointmentRepository_FindAndLock_Call) RunAndReturn(run func(string, *gorm.DB) (*entities.Appointment, error)) *AppointmentRepository_FindAndLock_Call {
	_c.Call.Return(run)
	return _c
}

// FindAppointmentByAppCode provides a mock function with given fields: appCode
func (_m *AppointmentRepository) FindAppointmentByAppCode(appCode string) (*entities.Appointment, error) {
	ret := _m.Called(appCode)

	if len(ret) == 0 {
		panic("no return value specified for FindAppointmentByAppCode")
	}

	var r0 *entities.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Appointment, error)); ok {
		return rf(appCode)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Appointment); ok {
		r0 = rf(appCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(appCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AppointmentRepository_FindAppointmentByAppCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAppointmentByAppCode'
type AppointmentRepository_FindAppointmentByAppCode_Call struct {
	*mock.Call
}

// FindAppointmentByAppCode is a helper method to define mock.On call
//   - appCode string
func (_e *AppointmentRepository_Expecter) FindAppointmentByAppCode(appCode interface{}) *AppointmentRepository_FindAppointmentByAppCode_Call {
	return &AppointmentRepository_FindAppointmentByAppCode_Call{Call: _e.mock.On("FindAppointmentByAppCode", appCode)}
}

func (_c *AppointmentRepository_FindAppointmentByAppCode_Call) Run(run func(appCode string)) *AppointmentRepository_FindAppointmentByAppCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AppointmentRepository_FindAppointmentByAppCode_Call) Return(_a0 *entities.Appointment, _a1 error) *AppointmentRepository_FindAppointmentByAppCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AppointmentRepository_FindAppointmentByAppCode_Call) RunAndReturn(run func(string) (*entities.Appointment, error)) *AppointmentRepository_FindAppointmentByAppCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppointmentsByOwnerIDQuery provides a mock function with given fields: ctx, ownerID
func (_m *AppointmentRepository) GetAppointmentsByOwnerIDQuery(ctx context.Context, ownerID uuid.UUID) paginate.Page {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetAppointmentsByOwnerIDQuery")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) paginate.Page); ok {
		r0 = rf(ctx, ownerID)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// AppointmentRepository_GetAppointmentsByOwnerIDQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppointmentsByOwnerIDQuery'
type AppointmentRepository_GetAppointmentsByOwnerIDQuery_Call struct {
	*mock.Call
}

// GetAppointmentsByOwnerIDQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
func (_e *AppointmentRepository_Expecter) GetAppointmentsByOwnerIDQuery(ctx interface{}, ownerID interface{}) *AppointmentRepository_GetAppointmentsByOwnerIDQuery_Call {
	return &AppointmentRepository_GetAppointmentsByOwnerIDQuery_Call{Call: _e.mock.On("GetAppointmentsByOwnerIDQuery", ctx, ownerID)}
}

func (_c *AppointmentRepository_GetAppointmentsByOwnerIDQuery_Call) Run(run func(ctx context.Context, ownerID uuid.UUID)) *AppointmentRepository_GetAppointmentsByOwnerIDQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AppointmentRepository_GetAppointmentsByOwnerIDQuery_Call) Return(_a0 paginate.Page) *AppointmentRepository_GetAppointmentsByOwnerIDQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppointmentRepository_GetAppointmentsByOwnerIDQuery_Call) RunAndReturn(run func(context.Context, uuid.UUID) paginate.Page) *AppointmentRepository_GetAppointmentsByOwnerIDQuery_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: appointment
func (_m *AppointmentRepository) Update(appointment *entities.Appointment) error {
	ret := _m.Called(appointment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Appointment) error); ok {
		r0 = rf(appointment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AppointmentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type AppointmentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - appointment *entities.Appointment
func (_e *AppointmentRepository_Expecter) Update(appointment interface{}) *AppointmentRepository_Update_Call {
	return &AppointmentRepository_Update_Call{Call: _e.mock.On("Update", appointment)}
}

func (_c *AppointmentRepository_Update_Call) Run(run func(appointment *entities.Appointment)) *AppointmentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Appointment))
	})
	return _c
}

func (_c *AppointmentRepository_Update_Call) Return(_a0 error) *AppointmentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppointmentRepository_Update_Call) RunAndReturn(run func(*entities.Appointment) error) *AppointmentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: tx
func (_m *AppointmentRepository) WithTx(tx *gorm.DB) repository.AppointmentRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.AppointmentRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.AppointmentRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.AppointmentRepository)
		}
	}

	return r0
}

// AppointmentRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type AppointmentRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *AppointmentRepository_Expecter) WithTx(tx interface{}) *AppointmentRepository_WithTx_Call {
	return &AppointmentRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *AppointmentRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *AppointmentRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *AppointmentRepository_WithTx_Call) Return(_a0 repository.AppointmentRepository) *AppointmentRepository_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppointmentRepository_WithTx_Call) RunAndReturn(run func(*gorm.DB) repository.AppointmentRepository) *AppointmentRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewAppointmentRepository creates a new instance of AppointmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppointmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppointmentRepository {
	mock := &AppointmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
