// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/m13ha/appointment_master/models/entities"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	paginate "github.com/morkid/paginate"

	repository "github.com/m13ha/appointment_master/repository"

	time "time"

	uuid "github.com/google/uuid"
)

// BookingRepository is an autogenerated mock type for the BookingRepository type
type BookingRepository struct {
	mock.Mock
}

type BookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BookingRepository) EXPECT() *BookingRepository_Expecter {
	return &BookingRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: booking
func (_m *BookingRepository) Create(booking *entities.Booking) error {
	ret := _m.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Booking) error); ok {
		r0 = rf(booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BookingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BookingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - booking *entities.Booking
func (_e *BookingRepository_Expecter) Create(booking interface{}) *BookingRepository_Create_Call {
	return &BookingRepository_Create_Call{Call: _e.mock.On("Create", booking)}
}

func (_c *BookingRepository_Create_Call) Run(run func(booking *entities.Booking)) *BookingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Booking))
	})
	return _c
}

func (_c *BookingRepository_Create_Call) Return(_a0 error) *BookingRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookingRepository_Create_Call) RunAndReturn(run func(*entities.Booking) error) *BookingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAvailableSlot provides a mock function with given fields: appCode, date, startTime
func (_m *BookingRepository) FindAvailableSlot(appCode string, date time.Time, startTime time.Time) (*entities.Booking, error) {
	ret := _m.Called(appCode, date, startTime)

	if len(ret) == 0 {
		panic("no return value specified for FindAvailableSlot")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) (*entities.Booking, error)); ok {
		return rf(appCode, date, startTime)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) *entities.Booking); ok {
		r0 = rf(appCode, date, startTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(appCode, date, startTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingRepository_FindAvailableSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAvailableSlot'
type BookingRepository_FindAvailableSlot_Call struct {
	*mock.Call
}

// FindAvailableSlot is a helper method to define mock.On call
//   - appCode string
//   - date time.Time
//   - startTime time.Time
func (_e *BookingRepository_Expecter) FindAvailableSlot(appCode interface{}, date interface{}, startTime interface{}) *BookingRepository_FindAvailableSlot_Call {
	return &BookingRepository_FindAvailableSlot_Call{Call: _e.mock.On("FindAvailableSlot", appCode, date, startTime)}
}

func (_c *BookingRepository_FindAvailableSlot_Call) Run(run func(appCode string, date time.Time, startTime time.Time)) *BookingRepository_FindAvailableSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *BookingRepository_FindAvailableSlot_Call) Return(_a0 *entities.Booking, _a1 error) *BookingRepository_FindAvailableSlot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingRepository_FindAvailableSlot_Call) RunAndReturn(run func(string, time.Time, time.Time) (*entities.Booking, error)) *BookingRepository_FindAvailableSlot_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailableSlots provides a mock function with given fields: ctx, appCode
func (_m *BookingRepository) GetAvailableSlots(ctx context.Context, appCode string) paginate.Page {
	ret := _m.Called(ctx, appCode)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSlots")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, string) paginate.Page); ok {
		r0 = rf(ctx, appCode)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// BookingRepository_GetAvailableSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableSlots'
type BookingRepository_GetAvailableSlots_Call struct {
	*mock.Call
}

// GetAvailableSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - appCode string
func (_e *BookingRepository_Expecter) GetAvailableSlots(ctx interface{}, appCode interface{}) *BookingRepository_GetAvailableSlots_Call {
	return &BookingRepository_GetAvailableSlots_Call{Call: _e.mock.On("GetAvailableSlots", ctx, appCode)}
}

func (_c *BookingRepository_GetAvailableSlots_Call) Run(run func(ctx context.Context, appCode string)) *BookingRepository_GetAvailableSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BookingRepository_GetAvailableSlots_Call) Return(_a0 paginate.Page) *BookingRepository_GetAvailableSlots_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookingRepository_GetAvailableSlots_Call) RunAndReturn(run func(context.Context, string) paginate.Page) *BookingRepository_GetAvailableSlots_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailableSlotsByDay provides a mock function with given fields: ctx, appCode, date
func (_m *BookingRepository) GetAvailableSlotsByDay(ctx context.Context, appCode string, date time.Time) paginate.Page {
	ret := _m.Called(ctx, appCode, date)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSlotsByDay")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) paginate.Page); ok {
		r0 = rf(ctx, appCode, date)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// BookingRepository_GetAvailableSlotsByDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableSlotsByDay'
type BookingRepository_GetAvailableSlotsByDay_Call struct {
	*mock.Call
}

// GetAvailableSlotsByDay is a helper method to define mock.On call
//   - ctx context.Context
//   - appCode string
//   - date time.Time
func (_e *BookingRepository_Expecter) GetAvailableSlotsByDay(ctx interface{}, appCode interface{}, date interface{}) *BookingRepository_GetAvailableSlotsByDay_Call {
	return &BookingRepository_GetAvailableSlotsByDay_Call{Call: _e.mock.On("GetAvailableSlotsByDay", ctx, appCode, date)}
}

func (_c *BookingRepository_GetAvailableSlotsByDay_Call) Run(run func(ctx context.Context, appCode string, date time.Time)) *BookingRepository_GetAvailableSlotsByDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *BookingRepository_GetAvailableSlotsByDay_Call) Return(_a0 paginate.Page) *BookingRepository_GetAvailableSlotsByDay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookingRepository_GetAvailableSlotsByDay_Call) RunAndReturn(run func(context.Context, string, time.Time) paginate.Page) *BookingRepository_GetAvailableSlotsByDay_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingByCode provides a mock function with given fields: bookingCode
func (_m *BookingRepository) GetBookingByCode(bookingCode string) (*entities.Booking, error) {
	ret := _m.Called(bookingCode)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByCode")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Booking, error)); ok {
		return rf(bookingCode)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Booking); ok {
		r0 = rf(bookingCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bookingCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookingRepository_GetBookingByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingByCode'
type BookingRepository_GetBookingByCode_Call struct {
	*mock.Call
}

// GetBookingByCode is a helper method to define mock.On call
//   - bookingCode string
func (_e *BookingRepository_Expecter) GetBookingByCode(bookingCode interface{}) *BookingRepository_GetBookingByCode_Call {
	return &BookingRepository_GetBookingByCode_Call{Call: _e.mock.On("GetBookingByCode", bookingCode)}
}

func (_c *BookingRepository_GetBookingByCode_Call) Run(run func(bookingCode string)) *BookingRepository_GetBookingByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *BookingRepository_GetBookingByCode_Call) Return(_a0 *entities.Booking, _a1 error) *BookingRepository_GetBookingByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookingRepository_GetBookingByCode_Call) RunAndReturn(run func(string) (*entities.Booking, error)) *BookingRepository_GetBookingByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsByAppCode provides a mock function with given fields: ctx, appCode, available
func (_m *BookingRepository) GetBookingsByAppCode(ctx context.Context, appCode string, available bool) paginate.Page {
	ret := _m.Called(ctx, appCode, available)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByAppCode")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) paginate.Page); ok {
		r0 = rf(ctx, appCode, available)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// BookingRepository_GetBookingsByAppCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsByAppCode'
type BookingRepository_GetBookingsByAppCode_Call struct {
	*mock.Call
}

// GetBookingsByAppCode is a helper method to define mock.On call
//   - ctx context.Context
//   - appCode string
//   - available bool
func (_e *BookingRepository_Expecter) GetBookingsByAppCode(ctx interface{}, appCode interface{}, available interface{}) *BookingRepository_GetBookingsByAppCode_Call {
	return &BookingRepository_GetBookingsByAppCode_Call{Call: _e.mock.On("GetBookingsByAppCode", ctx, appCode, available)}
}

func (_c *BookingRepository_GetBookingsByAppCode_Call) Run(run func(ctx context.Context, appCode string, available bool)) *BookingRepository_GetBookingsByAppCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *BookingRepository_GetBookingsByAppCode_Call) Return(_a0 paginate.Page) *BookingRepository_GetBookingsByAppCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookingRepository_GetBookingsByAppCode_Call) RunAndReturn(run func(context.Context, string, bool) paginate.Page) *BookingRepository_GetBookingsByAppCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsByUserID provides a mock function with given fields: ctx, userID
func (_m *BookingRepository) GetBookingsByUserID(ctx context.Context, userID uuid.UUID) paginate.Page {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByUserID")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) paginate.Page); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// BookingRepository_GetBookingsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsByUserID'
type BookingRepository_GetBookingsByUserID_Call struct {
	*mock.Call
}

// GetBookingsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *BookingRepository_Expecter) GetBookingsByUserID(ctx interface{}, userID interface{}) *BookingRepository_GetBookingsByUserID_Call {
	return &BookingRepository_GetBookingsByUserID_Call{Call: _e.mock.On("GetBookingsByUserID", ctx, userID)}
}

func (_c *BookingRepository_GetBookingsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *BookingRepository_GetBookingsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *BookingRepository_GetBookingsByUserID_Call) Return(_a0 paginate.Page) *BookingRepository_GetBookingsByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookingRepository_GetBookingsByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) paginate.Page) *BookingRepository_GetBookingsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: booking
func (_m *BookingRepository) Update(booking *entities.Booking) error {
	ret := _m.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Booking) error); ok {
		r0 = rf(booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BookingRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type BookingRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - booking *entities.Booking
func (_e *BookingRepository_Expecter) Update(booking interface{}) *BookingRepository_Update_Call {
	return &BookingRepository_Update_Call{Call: _e.mock.On("Update", booking)}
}

func (_c *BookingRepository_Update_Call) Run(run func(booking *entities.Booking)) *BookingRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Booking))
	})
	return _c
}

func (_c *BookingRepository_Update_Call) Return(_a0 error) *BookingRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookingRepository_Update_Call) RunAndReturn(run func(*entities.Booking) error) *BookingRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: tx
func (_m *BookingRepository) WithTx(tx *gorm.DB) repository.BookingRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.BookingRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.BookingRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.BookingRepository)
		}
	}

	return r0
}

// BookingRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type BookingRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *BookingRepository_Expecter) WithTx(tx interface{}) *BookingRepository_WithTx_Call {
	return &BookingRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *BookingRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *BookingRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *BookingRepository_WithTx_Call) Return(_a0 repository.BookingRepository) *BookingRepository_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookingRepository_WithTx_Call) RunAndReturn(run func(*gorm.DB) repository.BookingRepository) *BookingRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewBookingRepository creates a new instance of BookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingRepository {
	mock := &BookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
