/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntitiesAppointment,
  GetMyAppointments200Response,
  GetUserRegisteredBookings200Response,
  RequestsAppointmentRequest,
  ResponsesAPIErrorResponse,
} from '../models/index';
import {
    EntitiesAppointmentFromJSON,
    EntitiesAppointmentToJSON,
    GetMyAppointments200ResponseFromJSON,
    GetMyAppointments200ResponseToJSON,
    GetUserRegisteredBookings200ResponseFromJSON,
    GetUserRegisteredBookings200ResponseToJSON,
    RequestsAppointmentRequestFromJSON,
    RequestsAppointmentRequestToJSON,
    ResponsesAPIErrorResponseFromJSON,
    ResponsesAPIErrorResponseToJSON,
} from '../models/index';

export interface CreateAppointmentRequest {
    appointment: RequestsAppointmentRequest;
}

export interface DeleteAppointmentRequest {
    id: string;
}

export interface GetAppointmentByAppCodeRequest {
    appCode: string;
}

export interface GetMyAppointmentsRequest {
    status?: Array<string>;
    page?: number;
    size?: number;
}

export interface GetUsersRegisteredForAppointmentRequest {
    appCode: string;
    page?: number;
    size?: number;
}

export interface UpdateAppointmentRequest {
    id: string;
    appointment: RequestsAppointmentRequest;
}

/**
 * 
 */
export class AppointmentsApi extends runtime.BaseAPI {

    /**
     * Create a new appointment. Type can be single, group, or party.
     * Create a new appointment
     */
    async createAppointmentRaw(requestParameters: CreateAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitiesAppointment>> {
        if (requestParameters['appointment'] == null) {
            throw new runtime.RequiredError(
                'appointment',
                'Required parameter "appointment" was null or undefined when calling createAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/appointments`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestsAppointmentRequestToJSON(requestParameters['appointment']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitiesAppointmentFromJSON(jsonValue));
    }

    /**
     * Create a new appointment. Type can be single, group, or party.
     * Create a new appointment
     */
    async createAppointment(requestParameters: CreateAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitiesAppointment> {
        const response = await this.createAppointmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes an appointment and cancels all active bookings.
     * Delete an appointment
     */
    async deleteAppointmentRaw(requestParameters: DeleteAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitiesAppointment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/appointments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitiesAppointmentFromJSON(jsonValue));
    }

    /**
     * Deletes an appointment and cancels all active bookings.
     * Delete an appointment
     */
    async deleteAppointment(requestParameters: DeleteAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitiesAppointment> {
        const response = await this.deleteAppointmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves appointment details by its unique app_code, public endpoint for booking flow
     * Get appointment by app code
     */
    async getAppointmentByAppCodeRaw(requestParameters: GetAppointmentByAppCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitiesAppointment>> {
        if (requestParameters['appCode'] == null) {
            throw new runtime.RequiredError(
                'appCode',
                'Required parameter "appCode" was null or undefined when calling getAppointmentByAppCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/appointments/code/{app_code}`;
        urlPath = urlPath.replace(`{${"app_code"}}`, encodeURIComponent(String(requestParameters['appCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitiesAppointmentFromJSON(jsonValue));
    }

    /**
     * Retrieves appointment details by its unique app_code, public endpoint for booking flow
     * Get appointment by app code
     */
    async getAppointmentByAppCode(requestParameters: GetAppointmentByAppCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitiesAppointment> {
        const response = await this.getAppointmentByAppCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a paginated list of appointments created by the currently authenticated user.
     * Get appointments created by the user
     */
    async getMyAppointmentsRaw(requestParameters: GetMyAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetMyAppointments200Response>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/appointments/my`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetMyAppointments200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a paginated list of appointments created by the currently authenticated user.
     * Get appointments created by the user
     */
    async getMyAppointments(requestParameters: GetMyAppointmentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetMyAppointments200Response> {
        const response = await this.getMyAppointmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a paginated list of all users/bookings for a specific appointment.
     * Get all bookings for an appointment
     */
    async getUsersRegisteredForAppointmentRaw(requestParameters: GetUsersRegisteredForAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserRegisteredBookings200Response>> {
        if (requestParameters['appCode'] == null) {
            throw new runtime.RequiredError(
                'appCode',
                'Required parameter "appCode" was null or undefined when calling getUsersRegisteredForAppointment().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/appointments/users/{app_code}`;
        urlPath = urlPath.replace(`{${"app_code"}}`, encodeURIComponent(String(requestParameters['appCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUserRegisteredBookings200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a paginated list of all users/bookings for a specific appointment.
     * Get all bookings for an appointment
     */
    async getUsersRegisteredForAppointment(requestParameters: GetUsersRegisteredForAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserRegisteredBookings200Response> {
        const response = await this.getUsersRegisteredForAppointmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an appointment. Updates are blocked if any slot has been booked.
     * Update an appointment
     */
    async updateAppointmentRaw(requestParameters: UpdateAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitiesAppointment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAppointment().'
            );
        }

        if (requestParameters['appointment'] == null) {
            throw new runtime.RequiredError(
                'appointment',
                'Required parameter "appointment" was null or undefined when calling updateAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/appointments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RequestsAppointmentRequestToJSON(requestParameters['appointment']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitiesAppointmentFromJSON(jsonValue));
    }

    /**
     * Update an appointment. Updates are blocked if any slot has been booked.
     * Update an appointment
     */
    async updateAppointment(requestParameters: UpdateAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitiesAppointment> {
        const response = await this.updateAppointmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
