/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntitiesBooking,
  ErrorsAPIErrorResponse,
  GetUserRegisteredBookings200Response,
  RequestsBookingRequest,
} from '../models/index';
import {
    EntitiesBookingFromJSON,
    EntitiesBookingToJSON,
    ErrorsAPIErrorResponseFromJSON,
    ErrorsAPIErrorResponseToJSON,
    GetUserRegisteredBookings200ResponseFromJSON,
    GetUserRegisteredBookings200ResponseToJSON,
    RequestsBookingRequestFromJSON,
    RequestsBookingRequestToJSON,
} from '../models/index';

export interface BookGuestAppointmentRequest {
    booking: RequestsBookingRequest;
}

export interface BookRegisteredUserAppointmentRequest {
    booking: RequestsBookingRequest;
}

export interface CancelBookingByCodeRequest {
    bookingCode: string;
}

export interface GetAvailableSlotsRequest {
    appCode: string;
}

export interface GetAvailableSlotsByDayRequest {
    appCode: string;
    date: string;
}

export interface GetBookingByCodeRequest {
    bookingCode: string;
}

export interface RejectBookingByCodeRequest {
    bookingCode: string;
}

export interface UpdateBookingByCodeRequest {
    bookingCode: string;
    booking: RequestsBookingRequest;
}

/**
 * 
 */
export class BookingsApi extends runtime.BaseAPI {

    /**
     * Creates a booking for an appointment as a guest user. Name and email/phone are required.
     * Book an appointment (Guest)
     */
    async bookGuestAppointmentRaw(requestParameters: BookGuestAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitiesBooking>> {
        if (requestParameters['booking'] == null) {
            throw new runtime.RequiredError(
                'booking',
                'Required parameter "booking" was null or undefined when calling bookGuestAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/appointments/book`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestsBookingRequestToJSON(requestParameters['booking']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitiesBookingFromJSON(jsonValue));
    }

    /**
     * Creates a booking for an appointment as a guest user. Name and email/phone are required.
     * Book an appointment (Guest)
     */
    async bookGuestAppointment(requestParameters: BookGuestAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitiesBooking> {
        const response = await this.bookGuestAppointmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a booking for an appointment as a registered user.
     * Book an appointment (Registered User)
     */
    async bookRegisteredUserAppointmentRaw(requestParameters: BookRegisteredUserAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitiesBooking>> {
        if (requestParameters['booking'] == null) {
            throw new runtime.RequiredError(
                'booking',
                'Required parameter "booking" was null or undefined when calling bookRegisteredUserAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/appointments/book/registered`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestsBookingRequestToJSON(requestParameters['booking']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitiesBookingFromJSON(jsonValue));
    }

    /**
     * Creates a booking for an appointment as a registered user.
     * Book an appointment (Registered User)
     */
    async bookRegisteredUserAppointment(requestParameters: BookRegisteredUserAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitiesBooking> {
        const response = await this.bookRegisteredUserAppointmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Cancels a booking by its unique booking_code. This is a soft delete.
     * Cancel a booking
     */
    async cancelBookingByCodeRaw(requestParameters: CancelBookingByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitiesBooking>> {
        if (requestParameters['bookingCode'] == null) {
            throw new runtime.RequiredError(
                'bookingCode',
                'Required parameter "bookingCode" was null or undefined when calling cancelBookingByCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bookings/{booking_code}`;
        urlPath = urlPath.replace(`{${"booking_code"}}`, encodeURIComponent(String(requestParameters['bookingCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitiesBookingFromJSON(jsonValue));
    }

    /**
     * Cancels a booking by its unique booking_code. This is a soft delete.
     * Cancel a booking
     */
    async cancelBookingByCode(requestParameters: CancelBookingByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitiesBooking> {
        const response = await this.cancelBookingByCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a paginated list of all available booking slots for a given appointment.
     * Get available slots for an appointment
     */
    async getAvailableSlotsRaw(requestParameters: GetAvailableSlotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserRegisteredBookings200Response>> {
        if (requestParameters['appCode'] == null) {
            throw new runtime.RequiredError(
                'appCode',
                'Required parameter "appCode" was null or undefined when calling getAvailableSlots().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/appointments/slots/{app_code}`;
        urlPath = urlPath.replace(`{${"app_code"}}`, encodeURIComponent(String(requestParameters['appCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUserRegisteredBookings200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a paginated list of all available booking slots for a given appointment.
     * Get available slots for an appointment
     */
    async getAvailableSlots(requestParameters: GetAvailableSlotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserRegisteredBookings200Response> {
        const response = await this.getAvailableSlotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a paginated list of available slots for an appointment on a specific day.
     * Get available slots for a specific day
     */
    async getAvailableSlotsByDayRaw(requestParameters: GetAvailableSlotsByDayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserRegisteredBookings200Response>> {
        if (requestParameters['appCode'] == null) {
            throw new runtime.RequiredError(
                'appCode',
                'Required parameter "appCode" was null or undefined when calling getAvailableSlotsByDay().'
            );
        }

        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling getAvailableSlotsByDay().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/appointments/slots/{app_code}/by-day`;
        urlPath = urlPath.replace(`{${"app_code"}}`, encodeURIComponent(String(requestParameters['appCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUserRegisteredBookings200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a paginated list of available slots for an appointment on a specific day.
     * Get available slots for a specific day
     */
    async getAvailableSlotsByDay(requestParameters: GetAvailableSlotsByDayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserRegisteredBookings200Response> {
        const response = await this.getAvailableSlotsByDayRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves booking details by its unique booking_code.
     * Get booking by code
     */
    async getBookingByCodeRaw(requestParameters: GetBookingByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitiesBooking>> {
        if (requestParameters['bookingCode'] == null) {
            throw new runtime.RequiredError(
                'bookingCode',
                'Required parameter "bookingCode" was null or undefined when calling getBookingByCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bookings/{booking_code}`;
        urlPath = urlPath.replace(`{${"booking_code"}}`, encodeURIComponent(String(requestParameters['bookingCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitiesBookingFromJSON(jsonValue));
    }

    /**
     * Retrieves booking details by its unique booking_code.
     * Get booking by code
     */
    async getBookingByCode(requestParameters: GetBookingByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitiesBooking> {
        const response = await this.getBookingByCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a paginated list of all bookings made by the currently authenticated user.
     * Get user\'s registered bookings
     */
    async getUserRegisteredBookingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserRegisteredBookings200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/appointments/registered`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUserRegisteredBookings200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a paginated list of all bookings made by the currently authenticated user.
     * Get user\'s registered bookings
     */
    async getUserRegisteredBookings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserRegisteredBookings200Response> {
        const response = await this.getUserRegisteredBookingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Rejects a booking by its unique booking_code. This is a soft delete.
     * Reject a booking
     */
    async rejectBookingByCodeRaw(requestParameters: RejectBookingByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitiesBooking>> {
        if (requestParameters['bookingCode'] == null) {
            throw new runtime.RequiredError(
                'bookingCode',
                'Required parameter "bookingCode" was null or undefined when calling rejectBookingByCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/bookings/{booking_code}/reject`;
        urlPath = urlPath.replace(`{${"booking_code"}}`, encodeURIComponent(String(requestParameters['bookingCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitiesBookingFromJSON(jsonValue));
    }

    /**
     * Rejects a booking by its unique booking_code. This is a soft delete.
     * Reject a booking
     */
    async rejectBookingByCode(requestParameters: RejectBookingByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitiesBooking> {
        const response = await this.rejectBookingByCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a booking by its unique booking_code. Can be used to reschedule.
     * Update/Reschedule a booking
     */
    async updateBookingByCodeRaw(requestParameters: UpdateBookingByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitiesBooking>> {
        if (requestParameters['bookingCode'] == null) {
            throw new runtime.RequiredError(
                'bookingCode',
                'Required parameter "bookingCode" was null or undefined when calling updateBookingByCode().'
            );
        }

        if (requestParameters['booking'] == null) {
            throw new runtime.RequiredError(
                'booking',
                'Required parameter "booking" was null or undefined when calling updateBookingByCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/bookings/{booking_code}`;
        urlPath = urlPath.replace(`{${"booking_code"}}`, encodeURIComponent(String(requestParameters['bookingCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RequestsBookingRequestToJSON(requestParameters['booking']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitiesBookingFromJSON(jsonValue));
    }

    /**
     * Updates a booking by its unique booking_code. Can be used to reschedule.
     * Update/Reschedule a booking
     */
    async updateBookingByCode(requestParameters: UpdateBookingByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitiesBooking> {
        const response = await this.updateBookingByCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
