// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	repository "github.com/m13ha/asiko/repository"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// AnalyticsRepository is an autogenerated mock type for the AnalyticsRepository type
type AnalyticsRepository struct {
	mock.Mock
}

// GetAppointmentsByTypeCounts provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetAppointmentsByTypeCounts(userID uuid.UUID, startDate time.Time, endDate time.Time) (map[string]int, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAppointmentsByTypeCounts")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (map[string]int, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) map[string]int); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAvgAttendeesPerBooking provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetAvgAttendeesPerBooking(userID uuid.UUID, startDate time.Time, endDate time.Time) (float64, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAvgAttendeesPerBooking")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (float64, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) float64); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingsByStatusCounts provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetBookingsByStatusCounts(userID uuid.UUID, startDate time.Time, endDate time.Time) (map[string]int, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByStatusCounts")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (map[string]int, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) map[string]int); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingsPerDay provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetBookingsPerDay(userID uuid.UUID, startDate time.Time, endDate time.Time) ([]repository.DateCount, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsPerDay")
	}

	var r0 []repository.DateCount
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) ([]repository.DateCount, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) []repository.DateCount); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DateCount)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDistinctAndRepeatCustomers provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetDistinctAndRepeatCustomers(userID uuid.UUID, startDate time.Time, endDate time.Time) (int, int, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetDistinctAndRepeatCustomers")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (int, int, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) int); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) int); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r2 = rf(userID, startDate, endDate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetGuestVsRegisteredCounts provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetGuestVsRegisteredCounts(userID uuid.UUID, startDate time.Time, endDate time.Time) (map[string]int, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetGuestVsRegisteredCounts")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (map[string]int, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) map[string]int); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLeadTimeStatsHours provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetLeadTimeStatsHours(userID uuid.UUID, startDate time.Time, endDate time.Time) (float64, float64, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetLeadTimeStatsHours")
	}

	var r0 float64
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (float64, float64, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) float64); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) float64); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r2 = rf(userID, startDate, endDate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPartyCapacity provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetPartyCapacity(userID uuid.UUID, startDate time.Time, endDate time.Time) (int64, int64, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetPartyCapacity")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (int64, int64, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) int64); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) int64); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r2 = rf(userID, startDate, endDate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPeakDays provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetPeakDays(userID uuid.UUID, startDate time.Time, endDate time.Time) ([]repository.KeyCount, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetPeakDays")
	}

	var r0 []repository.KeyCount
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) ([]repository.KeyCount, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) []repository.KeyCount); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.KeyCount)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPeakHours provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetPeakHours(userID uuid.UUID, startDate time.Time, endDate time.Time) ([]repository.KeyCount, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetPeakHours")
	}

	var r0 []repository.KeyCount
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) ([]repository.KeyCount, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) []repository.KeyCount); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.KeyCount)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSlotUtilization provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetSlotUtilization(userID uuid.UUID, startDate time.Time, endDate time.Time) (int64, int64, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetSlotUtilization")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (int64, int64, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) int64); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) int64); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r2 = rf(userID, startDate, endDate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetStatusPerDay provides a mock function with given fields: userID, status, startDate, endDate
func (_m *AnalyticsRepository) GetStatusPerDay(userID uuid.UUID, status string, startDate time.Time, endDate time.Time) ([]repository.DateCount, error) {
	ret := _m.Called(userID, status, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusPerDay")
	}

	var r0 []repository.DateCount
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, time.Time, time.Time) ([]repository.DateCount, error)); ok {
		return rf(userID, status, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, time.Time, time.Time) []repository.DateCount); ok {
		r0 = rf(userID, status, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DateCount)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string, time.Time, time.Time) error); ok {
		r1 = rf(userID, status, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTopAppointments provides a mock function with given fields: userID, startDate, endDate, limit
func (_m *AnalyticsRepository) GetTopAppointments(userID uuid.UUID, startDate time.Time, endDate time.Time, limit int) ([]repository.TopAppointmentRow, error) {
	ret := _m.Called(userID, startDate, endDate, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTopAppointments")
	}

	var r0 []repository.TopAppointmentRow
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time, int) ([]repository.TopAppointmentRow, error)); ok {
		return rf(userID, startDate, endDate, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time, int) []repository.TopAppointmentRow); ok {
		r0 = rf(userID, startDate, endDate, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.TopAppointmentRow)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time, int) error); ok {
		r1 = rf(userID, startDate, endDate, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserAppointmentCount provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetUserAppointmentCount(userID uuid.UUID, startDate time.Time, endDate time.Time) (int64, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAppointmentCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (int64, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) int64); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserBookingCount provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetUserBookingCount(userID uuid.UUID, startDate time.Time, endDate time.Time) (int64, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBookingCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (int64, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) int64); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAnalyticsRepository creates a new instance of AnalyticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsRepository {
	mock := &AnalyticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
