// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// AnalyticsRepository is an autogenerated mock type for the AnalyticsRepository type
type AnalyticsRepository struct {
	mock.Mock
}

// GetUserAppointmentCount provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetUserAppointmentCount(userID uuid.UUID, startDate time.Time, endDate time.Time) (int64, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAppointmentCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (int64, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) int64); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserBookingCount provides a mock function with given fields: userID, startDate, endDate
func (_m *AnalyticsRepository) GetUserBookingCount(userID uuid.UUID, startDate time.Time, endDate time.Time) (int64, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBookingCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) (int64, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) int64); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAnalyticsRepository creates a new instance of AnalyticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsRepository {
	mock := &AnalyticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
