// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/m13ha/appointment_master/models/entities"
	"github.com/m13ha/appointment_master/repository"
	"github.com/morkid/paginate"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AppointmentRepository is an autogenerated mock type for the AppointmentRepository type
type AppointmentRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: appointment
func (_m *AppointmentRepository) Create(appointment *entities.Appointment) error {
	ret := _m.Called(appointment)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Appointment) error); ok {
		r0 = rf(appointment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAndLock provides a mock function with given fields: appCode, tx
func (_m *AppointmentRepository) FindAndLock(appCode string, tx *gorm.DB) (*entities.Appointment, error) {
	ret := _m.Called(appCode, tx)

	var r0 *entities.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *gorm.DB) (*entities.Appointment, error)); ok {
		return rf(appCode, tx)
	}
	if rf, ok := ret.Get(0).(func(string, *gorm.DB) *entities.Appointment); ok {
		r0 = rf(appCode, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *gorm.DB) error); ok {
		r1 = rf(appCode, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAppointmentByAppCode provides a mock function with given fields: appCode
func (_m *AppointmentRepository) FindAppointmentByAppCode(appCode string) (*entities.Appointment, error) {
	ret := _m.Called(appCode)

	var r0 *entities.Appointment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Appointment, error)); ok {
		return rf(appCode)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Appointment); ok {
		r0 = rf(appCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Appointment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(appCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAppointmentsByOwnerIDQuery provides a mock function with given fields: ctx, ownerID
func (_m *AppointmentRepository) GetAppointmentsByOwnerIDQuery(ctx context.Context, ownerID uuid.UUID) paginate.Page {
	ret := _m.Called(ctx, ownerID)

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) paginate.Page); ok {
		r0 = rf(ctx, ownerID)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// Update provides a mock function with given fields: appointment
func (_m *AppointmentRepository) Update(appointment *entities.Appointment) error {
	ret := _m.Called(appointment)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Appointment) error); ok {
		r0 = rf(appointment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *AppointmentRepository) WithTx(tx *gorm.DB) repository.AppointmentRepository {
	ret := _m.Called(tx)

	var r0 repository.AppointmentRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.AppointmentRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.AppointmentRepository)
		}
	}

	return r0
}