// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/m13ha/asiko/models/entities"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BanListRepository is an autogenerated mock type for the BanListRepository type
type BanListRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: entry
func (_m *BanListRepository) Create(entry *entities.BanListEntry) error {
	ret := _m.Called(entry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.BanListEntry) error); ok {
		r0 = rf(entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: userID, email
func (_m *BanListRepository) Delete(userID uuid.UUID, email string) error {
	ret := _m.Called(userID, email)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) error); ok {
		r0 = rf(userID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByUserAndEmail provides a mock function with given fields: userID, email
func (_m *BanListRepository) FindByUserAndEmail(userID uuid.UUID, email string) (*entities.BanListEntry, error) {
	ret := _m.Called(userID, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndEmail")
	}

	var r0 *entities.BanListEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (*entities.BanListEntry, error)); ok {
		return rf(userID, email)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) *entities.BanListEntry); ok {
		r0 = rf(userID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.BanListEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(userID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllByUser provides a mock function with given fields: userID
func (_m *BanListRepository) GetAllByUser(userID uuid.UUID) ([]entities.BanListEntry, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUser")
	}

	var r0 []entities.BanListEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]entities.BanListEntry, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []entities.BanListEntry); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.BanListEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBanListRepository creates a new instance of BanListRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBanListRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BanListRepository {
	mock := &BanListRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
