// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	"time"

	"github.com/m13ha/appointment_master/models/entities"
	"github.com/m13ha/appointment_master/repository"
	"github.com/morkid/paginate"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BookingRepository is an autogenerated mock type for the BookingRepository type
type BookingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: booking
func (_m *BookingRepository) Create(booking *entities.Booking) error {
	ret := _m.Called(booking)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Booking) error); ok {
		r0 = rf(booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAvailableSlot provides a mock function with given fields: appCode, date, startTime
func (_m *BookingRepository) FindAvailableSlot(appCode string, date time.Time, startTime time.Time) (*entities.Booking, error) {
	ret := _m.Called(appCode, date, startTime)

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) (*entities.Booking, error)); ok {
		return rf(appCode, date, startTime)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) *entities.Booking); ok {
		r0 = rf(appCode, date, startTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(appCode, date, startTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAvailableSlots provides a mock function with given fields: ctx, appCode
func (_m *BookingRepository) GetAvailableSlots(ctx context.Context, appCode string) paginate.Page {
	ret := _m.Called(ctx, appCode)

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, string) paginate.Page); ok {
		r0 = rf(ctx, appCode)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// GetAvailableSlotsByDay provides a mock function with given fields: ctx, appCode, date
func (_m *BookingRepository) GetAvailableSlotsByDay(ctx context.Context, appCode string, date time.Time) paginate.Page {
	ret := _m.Called(ctx, appCode, date)

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) paginate.Page); ok {
		r0 = rf(ctx, appCode, date)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// GetBookingByCode provides a mock function with given fields: bookingCode
func (_m *BookingRepository) GetBookingByCode(bookingCode string) (*entities.Booking, error) {
	ret := _m.Called(bookingCode)

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Booking, error)); ok {
		return rf(bookingCode)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Booking); ok {
		r0 = rf(bookingCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bookingCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingsByAppCode provides a mock function with given fields: ctx, appCode, available
func (_m *BookingRepository) GetBookingsByAppCode(ctx context.Context, appCode string, available bool) paginate.Page {
	ret := _m.Called(ctx, appCode, available)

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) paginate.Page); ok {
		r0 = rf(ctx, appCode, available)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// GetBookingsByUserID provides a mock function with given fields: ctx, userID
func (_m *BookingRepository) GetBookingsByUserID(ctx context.Context, userID uuid.UUID) paginate.Page {
	ret := _m.Called(ctx, userID)

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) paginate.Page); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// Update provides a mock function with given fields: booking
func (_m *BookingRepository) Update(booking *entities.Booking) error {
	ret := _m.Called(booking)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Booking) error); ok {
		r0 = rf(booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *BookingRepository) WithTx(tx *gorm.DB) repository.BookingRepository {
	ret := _m.Called(tx)

	var r0 repository.BookingRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.BookingRepository); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Get(0).(repository.BookingRepository)
	}

	return r0
}