// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/m13ha/asiko/models/entities"
	gorm "gorm.io/gorm"

	http "net/http"

	mock "github.com/stretchr/testify/mock"

	paginate "github.com/morkid/paginate"

	repository "github.com/m13ha/asiko/repository"

	time "time"

	uuid "github.com/google/uuid"
)

// BookingRepository is an autogenerated mock type for the BookingRepository type
type BookingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: booking
func (_m *BookingRepository) Create(booking *entities.Booking) error {
	ret := _m.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Booking) error); ok {
		r0 = rf(booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindActiveBookingByDevice provides a mock function with given fields: appointmentID, deviceID
func (_m *BookingRepository) FindActiveBookingByDevice(appointmentID uuid.UUID, deviceID string) (*entities.Booking, error) {
	ret := _m.Called(appointmentID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveBookingByDevice")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (*entities.Booking, error)); ok {
		return rf(appointmentID, deviceID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) *entities.Booking); ok {
		r0 = rf(appointmentID, deviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(appointmentID, deviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindActiveBookingByEmail provides a mock function with given fields: appointmentID, email
func (_m *BookingRepository) FindActiveBookingByEmail(appointmentID uuid.UUID, email string) (*entities.Booking, error) {
	ret := _m.Called(appointmentID, email)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveBookingByEmail")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (*entities.Booking, error)); ok {
		return rf(appointmentID, email)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) *entities.Booking); ok {
		r0 = rf(appointmentID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(appointmentID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindActiveBookingByPhone provides a mock function with given fields: appointmentID, phone
func (_m *BookingRepository) FindActiveBookingByPhone(appointmentID uuid.UUID, phone string) (*entities.Booking, error) {
	ret := _m.Called(appointmentID, phone)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveBookingByPhone")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (*entities.Booking, error)); ok {
		return rf(appointmentID, phone)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) *entities.Booking); ok {
		r0 = rf(appointmentID, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(appointmentID, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasActiveBookings provides a mock function with given fields: appointmentID
func (_m *BookingRepository) HasActiveBookings(appointmentID uuid.UUID) (bool, error) {
	ret := _m.Called(appointmentID)

	if len(ret) == 0 {
		panic("no return value specified for HasActiveBookings")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (bool, error)); ok {
		return rf(appointmentID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(appointmentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(appointmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveBookingsForAppointment provides a mock function with given fields: appointmentID
func (_m *BookingRepository) GetActiveBookingsForAppointment(appointmentID uuid.UUID) ([]entities.Booking, error) {
	ret := _m.Called(appointmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveBookingsForAppointment")
	}

	var r0 []entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]entities.Booking, error)); ok {
		return rf(appointmentID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []entities.Booking); ok {
		r0 = rf(appointmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(appointmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSlotsByAppointmentID provides a mock function with given fields: appointmentID
func (_m *BookingRepository) DeleteSlotsByAppointmentID(appointmentID uuid.UUID) error {
	ret := _m.Called(appointmentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSlotsByAppointmentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(appointmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAndLockAvailableSlot provides a mock function with given fields: appCode, date, startTime
func (_m *BookingRepository) FindAndLockAvailableSlot(appCode string, date time.Time, startTime time.Time) (*entities.Booking, error) {
	ret := _m.Called(appCode, date, startTime)

	if len(ret) == 0 {
		panic("no return value specified for FindAndLockAvailableSlot")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) (*entities.Booking, error)); ok {
		return rf(appCode, date, startTime)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) *entities.Booking); ok {
		r0 = rf(appCode, date, startTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(appCode, date, startTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAndLockSlot provides a mock function with given fields: appCode, date, startTime
func (_m *BookingRepository) FindAndLockSlot(appCode string, date time.Time, startTime time.Time) (*entities.Booking, error) {
	ret := _m.Called(appCode, date, startTime)

	if len(ret) == 0 {
		panic("no return value specified for FindAndLockSlot")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) (*entities.Booking, error)); ok {
		return rf(appCode, date, startTime)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) *entities.Booking); ok {
		r0 = rf(appCode, date, startTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(appCode, date, startTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAvailableSlot provides a mock function with given fields: appCode, date, startTime
func (_m *BookingRepository) FindAvailableSlot(appCode string, date time.Time, startTime time.Time) (*entities.Booking, error) {
	ret := _m.Called(appCode, date, startTime)

	if len(ret) == 0 {
		panic("no return value specified for FindAvailableSlot")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) (*entities.Booking, error)); ok {
		return rf(appCode, date, startTime)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) *entities.Booking); ok {
		r0 = rf(appCode, date, startTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(appCode, date, startTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAvailableSlots provides a mock function with given fields: ctx, req, appCode
func (_m *BookingRepository) GetAvailableSlots(ctx context.Context, req *http.Request, appCode string) paginate.Page {
	ret := _m.Called(ctx, req, appCode)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSlots")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request, string) paginate.Page); ok {
		r0 = rf(ctx, req, appCode)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// GetAvailableSlotsByDay provides a mock function with given fields: ctx, req, appCode, date
func (_m *BookingRepository) GetAvailableSlotsByDay(ctx context.Context, req *http.Request, appCode string, date time.Time) paginate.Page {
	ret := _m.Called(ctx, req, appCode, date)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSlotsByDay")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request, string, time.Time) paginate.Page); ok {
		r0 = rf(ctx, req, appCode, date)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// GetBookingByCode provides a mock function with given fields: bookingCode
func (_m *BookingRepository) GetBookingByCode(bookingCode string) (*entities.Booking, error) {
	ret := _m.Called(bookingCode)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByCode")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Booking, error)); ok {
		return rf(bookingCode)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Booking); ok {
		r0 = rf(bookingCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bookingCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingsByAppCode provides a mock function with given fields: ctx, req, appCode, available
func (_m *BookingRepository) GetBookingsByAppCode(ctx context.Context, req *http.Request, appCode string, available bool) paginate.Page {
	ret := _m.Called(ctx, req, appCode, available)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByAppCode")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request, string, bool) paginate.Page); ok {
		r0 = rf(ctx, req, appCode, available)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// GetBookingsByUserID provides a mock function with given fields: ctx, req, userID, statuses
func (_m *BookingRepository) GetBookingsByUserID(ctx context.Context, req *http.Request, userID uuid.UUID, statuses []string) paginate.Page {
	ret := _m.Called(ctx, req, userID, statuses)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByUserID")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request, uuid.UUID, []string) paginate.Page); ok {
		r0 = rf(ctx, req, userID, statuses)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// MarkBookingsOngoing provides a mock function with given fields: ctx, now
func (_m *BookingRepository) MarkBookingsOngoing(ctx context.Context, now time.Time) (int64, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkBookingsOngoing")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, now)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkBookingsExpired provides a mock function with given fields: ctx, now
func (_m *BookingRepository) MarkBookingsExpired(ctx context.Context, now time.Time) (int64, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkBookingsExpired")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, now)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: booking
func (_m *BookingRepository) Update(booking *entities.Booking) error {
	ret := _m.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Booking) error); ok {
		r0 = rf(booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateNotificationStatus provides a mock function with given fields: id, status, channel
func (_m *BookingRepository) UpdateNotificationStatus(id uuid.UUID, status string, channel string) error {
	ret := _m.Called(id, status, channel)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string) error); ok {
		r0 = rf(id, status, channel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAvailableDates provides a mock function with given fields: ctx, appCode
func (_m *BookingRepository) GetAvailableDates(ctx context.Context, appCode string) ([]time.Time, error) {
	ret := _m.Called(ctx, appCode)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableDates")
	}

	var r0 []time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]time.Time, error)); ok {
		return rf(ctx, appCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []time.Time); ok {
		r0 = rf(ctx, appCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, appCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithTx provides a mock function with given fields: tx
func (_m *BookingRepository) WithTx(tx *gorm.DB) repository.BookingRepository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.BookingRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.BookingRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.BookingRepository)
		}
	}

	return r0
}

// NewBookingRepository creates a new instance of BookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingRepository {
	mock := &BookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
