// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/m13ha/asiko/models/entities"
	mock "github.com/stretchr/testify/mock"

	paginate "github.com/morkid/paginate"

	uuid "github.com/google/uuid"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: notification
func (_m *NotificationRepository) Create(notification *entities.Notification) error {
	ret := _m.Called(notification)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Notification) error); ok {
		r0 = rf(notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *NotificationRepository) GetByUserID(ctx context.Context, userID uuid.UUID) paginate.Page {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) paginate.Page); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// MarkAllAsRead provides a mock function with given fields: userID
func (_m *NotificationRepository) MarkAllAsRead(userID uuid.UUID) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
