// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/m13ha/asiko/models/entities"
	mock "github.com/stretchr/testify/mock"
)

// PendingUserRepository is an autogenerated mock type for the PendingUserRepository type
type PendingUserRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: user
func (_m *PendingUserRepository) Create(user *entities.PendingUser) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.PendingUser) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: email
func (_m *PendingUserRepository) Delete(email string) error {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEmail provides a mock function with given fields: email
func (_m *PendingUserRepository) FindByEmail(email string) (*entities.PendingUser, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entities.PendingUser
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.PendingUser, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.PendingUser); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.PendingUser)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: user
func (_m *PendingUserRepository) Update(user *entities.PendingUser) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.PendingUser) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPendingUserRepository creates a new instance of PendingUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPendingUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PendingUserRepository {
	mock := &PendingUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
