/* tslint:disable */
/* eslint-disable */
/**
 * Appointment Master API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EntitiesAppointmentType = {
    Single: 'single',
    Group: 'group',
    Party: 'party'
} as const;
export type EntitiesAppointmentType = typeof EntitiesAppointmentType[keyof typeof EntitiesAppointmentType];


export function instanceOfEntitiesAppointmentType(value: any): boolean {
    for (const key in EntitiesAppointmentType) {
        if (Object.prototype.hasOwnProperty.call(EntitiesAppointmentType, key)) {
            if (EntitiesAppointmentType[key as keyof typeof EntitiesAppointmentType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EntitiesAppointmentTypeFromJSON(json: any): EntitiesAppointmentType {
    return EntitiesAppointmentTypeFromJSONTyped(json, false);
}

export function EntitiesAppointmentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntitiesAppointmentType {
    return json as EntitiesAppointmentType;
}

export function EntitiesAppointmentTypeToJSON(value?: EntitiesAppointmentType | null): any {
    return value as any;
}

export function EntitiesAppointmentTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): EntitiesAppointmentType {
    return value as EntitiesAppointmentType;
}

