/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntitiesBooking
 */
export interface EntitiesBooking {
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    appCode?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    appointmentId?: string;
    /**
     * 
     * @type {number}
     * @memberof EntitiesBooking
     */
    attendeeCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EntitiesBooking
     */
    available?: boolean;
    /**
     * Permanent booking code for all bookings
     * @type {string}
     * @memberof EntitiesBooking
     */
    bookingCode?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    date?: string;
    /**
     * 
     * @type {Date}
     * @memberof EntitiesBooking
     */
    deletedAt?: Date;
    /**
     * Additional info from the booker
     * @type {string}
     * @memberof EntitiesBooking
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    endTime?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    notificationChannel?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    notificationStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    startTime?: string;
    /**
     * Booking status: active, cancelled, etc.
     * @type {string}
     * @memberof EntitiesBooking
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBooking
     */
    userId?: string;
}

/**
 * Check if a given object implements the EntitiesBooking interface.
 */
export function instanceOfEntitiesBooking(value: object): value is EntitiesBooking {
    return true;
}

export function EntitiesBookingFromJSON(json: any): EntitiesBooking {
    return EntitiesBookingFromJSONTyped(json, false);
}

export function EntitiesBookingFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntitiesBooking {
    if (json == null) {
        return json;
    }
    return {
        
        'appCode': json['app_code'] == null ? undefined : json['app_code'],
        'appointmentId': json['appointment_id'] == null ? undefined : json['appointment_id'],
        'attendeeCount': json['attendee_count'] == null ? undefined : json['attendee_count'],
        'available': json['available'] == null ? undefined : json['available'],
        'bookingCode': json['booking_code'] == null ? undefined : json['booking_code'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'date': json['date'] == null ? undefined : json['date'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'email': json['email'] == null ? undefined : json['email'],
        'endTime': json['end_time'] == null ? undefined : json['end_time'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'notificationChannel': json['notification_channel'] == null ? undefined : json['notification_channel'],
        'notificationStatus': json['notification_status'] == null ? undefined : json['notification_status'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function EntitiesBookingToJSON(json: any): EntitiesBooking {
    return EntitiesBookingToJSONTyped(json, false);
}

export function EntitiesBookingToJSONTyped(value?: EntitiesBooking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_code': value['appCode'],
        'appointment_id': value['appointmentId'],
        'attendee_count': value['attendeeCount'],
        'available': value['available'],
        'booking_code': value['bookingCode'],
        'created_at': value['createdAt'],
        'date': value['date'],
        'deleted_at': value['deletedAt'] == null ? undefined : ((value['deletedAt']).toISOString()),
        'description': value['description'],
        'email': value['email'],
        'end_time': value['endTime'],
        'id': value['id'],
        'name': value['name'],
        'notification_channel': value['notificationChannel'],
        'notification_status': value['notificationStatus'],
        'phone': value['phone'],
        'start_time': value['startTime'],
        'status': value['status'],
        'updated_at': value['updatedAt'],
        'user_id': value['userId'],
    };
}

