/* tslint:disable */
/* eslint-disable */
/**
 * Appointment Master API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorsApiErrorResponse
 */
export interface ErrorsApiErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorsApiErrorResponse
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorsApiErrorResponse
     */
    details?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorsApiErrorResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the ErrorsApiErrorResponse interface.
 */
export function instanceOfErrorsApiErrorResponse(value: object): value is ErrorsApiErrorResponse {
    return true;
}

export function ErrorsApiErrorResponseFromJSON(json: any): ErrorsApiErrorResponse {
    return ErrorsApiErrorResponseFromJSONTyped(json, false);
}

export function ErrorsApiErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorsApiErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'details': json['details'] == null ? undefined : json['details'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ErrorsApiErrorResponseToJSON(json: any): ErrorsApiErrorResponse {
    return ErrorsApiErrorResponseToJSONTyped(json, false);
}

export function ErrorsApiErrorResponseToJSONTyped(value?: ErrorsApiErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'details': value['details'],
        'message': value['message'],
    };
}

