/* tslint:disable */
/* eslint-disable */
/**
 * Appointment Master API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntitiesBooking } from './EntitiesBooking';
import {
    EntitiesBookingFromJSON,
    EntitiesBookingFromJSONTyped,
    EntitiesBookingToJSON,
    EntitiesBookingToJSONTyped,
} from './EntitiesBooking';

/**
 * 
 * @export
 * @interface GetUserRegisteredBookings200Response
 */
export interface GetUserRegisteredBookings200Response {
    /**
     * 
     * @type {Array<EntitiesBooking>}
     * @memberof GetUserRegisteredBookings200Response
     */
    items?: Array<EntitiesBooking>;
    /**
     * 
     * @type {number}
     * @memberof GetUserRegisteredBookings200Response
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUserRegisteredBookings200Response
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUserRegisteredBookings200Response
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUserRegisteredBookings200Response
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the GetUserRegisteredBookings200Response interface.
 */
export function instanceOfGetUserRegisteredBookings200Response(value: object): value is GetUserRegisteredBookings200Response {
    return true;
}

export function GetUserRegisteredBookings200ResponseFromJSON(json: any): GetUserRegisteredBookings200Response {
    return GetUserRegisteredBookings200ResponseFromJSONTyped(json, false);
}

export function GetUserRegisteredBookings200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserRegisteredBookings200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(EntitiesBookingFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'total': json['total'] == null ? undefined : json['total'],
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
    };
}

export function GetUserRegisteredBookings200ResponseToJSON(json: any): GetUserRegisteredBookings200Response {
    return GetUserRegisteredBookings200ResponseToJSONTyped(json, false);
}

export function GetUserRegisteredBookings200ResponseToJSONTyped(value?: GetUserRegisteredBookings200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(EntitiesBookingToJSON)),
        'page': value['page'],
        'per_page': value['perPage'],
        'total': value['total'],
        'total_pages': value['totalPages'],
    };
}

