/* tslint:disable */
/* eslint-disable */
/**
 * Appointment Master API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestsLoginRequest
 */
export interface RequestsLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsLoginRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsLoginRequest
     */
    password: string;
}

/**
 * Check if a given object implements the RequestsLoginRequest interface.
 */
export function instanceOfRequestsLoginRequest(value: object): value is RequestsLoginRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RequestsLoginRequestFromJSON(json: any): RequestsLoginRequest {
    return RequestsLoginRequestFromJSONTyped(json, false);
}

export function RequestsLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function RequestsLoginRequestToJSON(json: any): RequestsLoginRequest {
    return RequestsLoginRequestToJSONTyped(json, false);
}

export function RequestsLoginRequestToJSONTyped(value?: RequestsLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

