/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntitiesAppointmentType } from './EntitiesAppointmentType';
import {
    EntitiesAppointmentTypeFromJSON,
    EntitiesAppointmentTypeFromJSONTyped,
    EntitiesAppointmentTypeToJSON,
    EntitiesAppointmentTypeToJSONTyped,
} from './EntitiesAppointmentType';

/**
 * 
 * @export
 * @interface RequestsAppointmentRequest
 */
export interface RequestsAppointmentRequest {
    /**
     * 
     * @type {number}
     * @memberof RequestsAppointmentRequest
     */
    bookingDuration: number;
    /**
     * 
     * @type {string}
     * @memberof RequestsAppointmentRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsAppointmentRequest
     */
    endDate: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsAppointmentRequest
     */
    endTime: string;
    /**
     * 
     * @type {number}
     * @memberof RequestsAppointmentRequest
     */
    maxAttendees?: number;
    /**
     * 
     * @type {string}
     * @memberof RequestsAppointmentRequest
     */
    startDate: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsAppointmentRequest
     */
    startTime: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsAppointmentRequest
     */
    title: string;
    /**
     * 
     * @type {EntitiesAppointmentType}
     * @memberof RequestsAppointmentRequest
     */
    type: EntitiesAppointmentType;
}



/**
 * Check if a given object implements the RequestsAppointmentRequest interface.
 */
export function instanceOfRequestsAppointmentRequest(value: object): value is RequestsAppointmentRequest {
    if (!('bookingDuration' in value) || value['bookingDuration'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RequestsAppointmentRequestFromJSON(json: any): RequestsAppointmentRequest {
    return RequestsAppointmentRequestFromJSONTyped(json, false);
}

export function RequestsAppointmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsAppointmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bookingDuration': json['booking_duration'],
        'description': json['description'] == null ? undefined : json['description'],
        'endDate': json['end_date'],
        'endTime': json['end_time'],
        'maxAttendees': json['max_attendees'] == null ? undefined : json['max_attendees'],
        'startDate': json['start_date'],
        'startTime': json['start_time'],
        'title': json['title'],
        'type': EntitiesAppointmentTypeFromJSON(json['type']),
    };
}

export function RequestsAppointmentRequestToJSON(json: any): RequestsAppointmentRequest {
    return RequestsAppointmentRequestToJSONTyped(json, false);
}

export function RequestsAppointmentRequestToJSONTyped(value?: RequestsAppointmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'booking_duration': value['bookingDuration'],
        'description': value['description'],
        'end_date': value['endDate'],
        'end_time': value['endTime'],
        'max_attendees': value['maxAttendees'],
        'start_date': value['startDate'],
        'start_time': value['startTime'],
        'title': value['title'],
        'type': EntitiesAppointmentTypeToJSON(value['type']),
    };
}

