/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesAnalyticsResponse
 */
export interface ResponsesAnalyticsResponse {
    /**
     * 
     * @type {string}
     * @memberof ResponsesAnalyticsResponse
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAnalyticsResponse
     */
    startDate?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesAnalyticsResponse
     */
    totalAppointments?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsesAnalyticsResponse
     */
    totalBookings?: number;
}

/**
 * Check if a given object implements the ResponsesAnalyticsResponse interface.
 */
export function instanceOfResponsesAnalyticsResponse(value: object): value is ResponsesAnalyticsResponse {
    return true;
}

export function ResponsesAnalyticsResponseFromJSON(json: any): ResponsesAnalyticsResponse {
    return ResponsesAnalyticsResponseFromJSONTyped(json, false);
}

export function ResponsesAnalyticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesAnalyticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'totalAppointments': json['total_appointments'] == null ? undefined : json['total_appointments'],
        'totalBookings': json['total_bookings'] == null ? undefined : json['total_bookings'],
    };
}

export function ResponsesAnalyticsResponseToJSON(json: any): ResponsesAnalyticsResponse {
    return ResponsesAnalyticsResponseToJSONTyped(json, false);
}

export function ResponsesAnalyticsResponseToJSONTyped(value?: ResponsesAnalyticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end_date': value['endDate'],
        'start_date': value['startDate'],
        'total_appointments': value['totalAppointments'],
        'total_bookings': value['totalBookings'],
    };
}

