/* tslint:disable */
/* eslint-disable */
/**
 * Appointment Master API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesSimpleMessageResponse
 */
export interface ResponsesSimpleMessageResponse {
    /**
     * 
     * @type {string}
     * @memberof ResponsesSimpleMessageResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the ResponsesSimpleMessageResponse interface.
 */
export function instanceOfResponsesSimpleMessageResponse(value: object): value is ResponsesSimpleMessageResponse {
    return true;
}

export function ResponsesSimpleMessageResponseFromJSON(json: any): ResponsesSimpleMessageResponse {
    return ResponsesSimpleMessageResponseFromJSONTyped(json, false);
}

export function ResponsesSimpleMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesSimpleMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ResponsesSimpleMessageResponseToJSON(json: any): ResponsesSimpleMessageResponse {
    return ResponsesSimpleMessageResponseToJSONTyped(json, false);
}

export function ResponsesSimpleMessageResponseToJSONTyped(value?: ResponsesSimpleMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

