/* tslint:disable */
/* eslint-disable */
/**
 * Appointment Master API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesPaginatedResponse
 */
export interface ResponsesPaginatedResponse {
    /**
     * 
     * @type {Array<object>}
     * @memberof ResponsesPaginatedResponse
     */
    items?: Array<object>;
    /**
     * 
     * @type {number}
     * @memberof ResponsesPaginatedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsesPaginatedResponse
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsesPaginatedResponse
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsesPaginatedResponse
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the ResponsesPaginatedResponse interface.
 */
export function instanceOfResponsesPaginatedResponse(value: object): value is ResponsesPaginatedResponse {
    return true;
}

export function ResponsesPaginatedResponseFromJSON(json: any): ResponsesPaginatedResponse {
    return ResponsesPaginatedResponseFromJSONTyped(json, false);
}

export function ResponsesPaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesPaginatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : json['items'],
        'page': json['page'] == null ? undefined : json['page'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'total': json['total'] == null ? undefined : json['total'],
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
    };
}

export function ResponsesPaginatedResponseToJSON(json: any): ResponsesPaginatedResponse {
    return ResponsesPaginatedResponseToJSONTyped(json, false);
}

export function ResponsesPaginatedResponseToJSONTyped(value?: ResponsesPaginatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'],
        'page': value['page'],
        'per_page': value['perPage'],
        'total': value['total'],
        'total_pages': value['totalPages'],
    };
}

