/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EntitiesAntiScalpingLevel = {
    ScalpingNone: 'none',
    ScalpingStandard: 'standard',
    ScalpingStrict: 'strict'
} as const;
export type EntitiesAntiScalpingLevel = typeof EntitiesAntiScalpingLevel[keyof typeof EntitiesAntiScalpingLevel];


export function instanceOfEntitiesAntiScalpingLevel(value: any): boolean {
    for (const key in EntitiesAntiScalpingLevel) {
        if (Object.prototype.hasOwnProperty.call(EntitiesAntiScalpingLevel, key)) {
            if (EntitiesAntiScalpingLevel[key as keyof typeof EntitiesAntiScalpingLevel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EntitiesAntiScalpingLevelFromJSON(json: any): EntitiesAntiScalpingLevel {
    return EntitiesAntiScalpingLevelFromJSONTyped(json, false);
}

export function EntitiesAntiScalpingLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntitiesAntiScalpingLevel {
    return json as EntitiesAntiScalpingLevel;
}

export function EntitiesAntiScalpingLevelToJSON(value?: EntitiesAntiScalpingLevel | null): any {
    return value as any;
}

export function EntitiesAntiScalpingLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): EntitiesAntiScalpingLevel {
    return value as EntitiesAntiScalpingLevel;
}

