/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntitiesNotification
 */
export interface EntitiesNotification {
    /**
     * 
     * @type {string}
     * @memberof EntitiesNotification
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesNotification
     */
    eventType?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesNotification
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntitiesNotification
     */
    isRead?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EntitiesNotification
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesNotification
     */
    resourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesNotification
     */
    userId?: string;
}

/**
 * Check if a given object implements the EntitiesNotification interface.
 */
export function instanceOfEntitiesNotification(value: object): value is EntitiesNotification {
    return true;
}

export function EntitiesNotificationFromJSON(json: any): EntitiesNotification {
    return EntitiesNotificationFromJSONTyped(json, false);
}

export function EntitiesNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntitiesNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'eventType': json['event_type'] == null ? undefined : json['event_type'],
        'id': json['id'] == null ? undefined : json['id'],
        'isRead': json['is_read'] == null ? undefined : json['is_read'],
        'message': json['message'] == null ? undefined : json['message'],
        'resourceId': json['resource_id'] == null ? undefined : json['resource_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function EntitiesNotificationToJSON(json: any): EntitiesNotification {
    return EntitiesNotificationToJSONTyped(json, false);
}

export function EntitiesNotificationToJSONTyped(value?: EntitiesNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'event_type': value['eventType'],
        'id': value['id'],
        'is_read': value['isRead'],
        'message': value['message'],
        'resource_id': value['resourceId'],
        'user_id': value['userId'],
    };
}

