/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EntitiesAppointmentStatus = {
    AppointmentStatusPending: 'pending',
    AppointmentStatusOngoing: 'ongoing',
    AppointmentStatusCompleted: 'completed',
    AppointmentStatusCanceled: 'canceled',
    AppointmentStatusExpired: 'expired'
} as const;
export type EntitiesAppointmentStatus = typeof EntitiesAppointmentStatus[keyof typeof EntitiesAppointmentStatus];


export function instanceOfEntitiesAppointmentStatus(value: any): boolean {
    for (const key in EntitiesAppointmentStatus) {
        if (Object.prototype.hasOwnProperty.call(EntitiesAppointmentStatus, key)) {
            if (EntitiesAppointmentStatus[key as keyof typeof EntitiesAppointmentStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EntitiesAppointmentStatusFromJSON(json: any): EntitiesAppointmentStatus {
    return EntitiesAppointmentStatusFromJSONTyped(json, false);
}

export function EntitiesAppointmentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntitiesAppointmentStatus {
    return json as EntitiesAppointmentStatus;
}

export function EntitiesAppointmentStatusToJSON(value?: EntitiesAppointmentStatus | null): any {
    return value as any;
}

export function EntitiesAppointmentStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): EntitiesAppointmentStatus {
    return value as EntitiesAppointmentStatus;
}

