/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntitiesBanListEntry
 */
export interface EntitiesBanListEntry {
    /**
     * 
     * @type {string}
     * @memberof EntitiesBanListEntry
     */
    bannedEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBanListEntry
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBanListEntry
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesBanListEntry
     */
    userId?: string;
}

/**
 * Check if a given object implements the EntitiesBanListEntry interface.
 */
export function instanceOfEntitiesBanListEntry(value: object): value is EntitiesBanListEntry {
    return true;
}

export function EntitiesBanListEntryFromJSON(json: any): EntitiesBanListEntry {
    return EntitiesBanListEntryFromJSONTyped(json, false);
}

export function EntitiesBanListEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntitiesBanListEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'bannedEmail': json['banned_email'] == null ? undefined : json['banned_email'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function EntitiesBanListEntryToJSON(json: any): EntitiesBanListEntry {
    return EntitiesBanListEntryToJSONTyped(json, false);
}

export function EntitiesBanListEntryToJSONTyped(value?: EntitiesBanListEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'banned_email': value['bannedEmail'],
        'created_at': value['createdAt'],
        'id': value['id'],
        'user_id': value['userId'],
    };
}

