/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntitiesAntiScalpingLevel } from './EntitiesAntiScalpingLevel';
import {
    EntitiesAntiScalpingLevelFromJSON,
    EntitiesAntiScalpingLevelFromJSONTyped,
    EntitiesAntiScalpingLevelToJSON,
    EntitiesAntiScalpingLevelToJSONTyped,
} from './EntitiesAntiScalpingLevel';
import type { EntitiesAppointmentType } from './EntitiesAppointmentType';
import {
    EntitiesAppointmentTypeFromJSON,
    EntitiesAppointmentTypeFromJSONTyped,
    EntitiesAppointmentTypeToJSON,
    EntitiesAppointmentTypeToJSONTyped,
} from './EntitiesAppointmentType';
import type { EntitiesAppointmentStatus } from './EntitiesAppointmentStatus';
import {
    EntitiesAppointmentStatusFromJSON,
    EntitiesAppointmentStatusFromJSONTyped,
    EntitiesAppointmentStatusToJSON,
    EntitiesAppointmentStatusToJSONTyped,
} from './EntitiesAppointmentStatus';
import type { EntitiesBooking } from './EntitiesBooking';
import {
    EntitiesBookingFromJSON,
    EntitiesBookingFromJSONTyped,
    EntitiesBookingToJSON,
    EntitiesBookingToJSONTyped,
} from './EntitiesBooking';

/**
 * 
 * @export
 * @interface EntitiesAppointment
 */
export interface EntitiesAppointment {
    /**
     * 
     * @type {EntitiesAntiScalpingLevel}
     * @memberof EntitiesAppointment
     */
    antiScalpingLevel?: EntitiesAntiScalpingLevel;
    /**
     * 
     * @type {string}
     * @memberof EntitiesAppointment
     */
    appCode?: string;
    /**
     * 
     * @type {number}
     * @memberof EntitiesAppointment
     */
    attendeesBooked?: number;
    /**
     * in minutes
     * @type {number}
     * @memberof EntitiesAppointment
     */
    bookingDuration?: number;
    /**
     * 
     * @type {Array<EntitiesBooking>}
     * @memberof EntitiesAppointment
     */
    bookings?: Array<EntitiesBooking>;
    /**
     * 
     * @type {string}
     * @memberof EntitiesAppointment
     */
    createdAt?: string;
    /**
     * 
     * @type {Date}
     * @memberof EntitiesAppointment
     */
    deletedAt?: Date;
    /**
     * Additional info for the appointment
     * @type {string}
     * @memberof EntitiesAppointment
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesAppointment
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesAppointment
     */
    endTime?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesAppointment
     */
    id?: string;
    /**
     * for group appointments
     * @type {number}
     * @memberof EntitiesAppointment
     */
    maxAttendees?: number;
    /**
     * 
     * @type {string}
     * @memberof EntitiesAppointment
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesAppointment
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitiesAppointment
     */
    startTime?: string;
    /**
     * 
     * @type {EntitiesAppointmentStatus}
     * @memberof EntitiesAppointment
     */
    status?: EntitiesAppointmentStatus;
    /**
     * 
     * @type {string}
     * @memberof EntitiesAppointment
     */
    title?: string;
    /**
     * 
     * @type {EntitiesAppointmentType}
     * @memberof EntitiesAppointment
     */
    type?: EntitiesAppointmentType;
    /**
     * 
     * @type {string}
     * @memberof EntitiesAppointment
     */
    updatedAt?: string;
}



/**
 * Check if a given object implements the EntitiesAppointment interface.
 */
export function instanceOfEntitiesAppointment(value: object): value is EntitiesAppointment {
    return true;
}

export function EntitiesAppointmentFromJSON(json: any): EntitiesAppointment {
    return EntitiesAppointmentFromJSONTyped(json, false);
}

export function EntitiesAppointmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntitiesAppointment {
    if (json == null) {
        return json;
    }
    return {
        
        'antiScalpingLevel': json['anti_scalping_level'] == null ? undefined : EntitiesAntiScalpingLevelFromJSON(json['anti_scalping_level']),
        'appCode': json['app_code'] == null ? undefined : json['app_code'],
        'attendeesBooked': json['attendees_booked'] == null ? undefined : json['attendees_booked'],
        'bookingDuration': json['booking_duration'] == null ? undefined : json['booking_duration'],
        'bookings': json['bookings'] == null ? undefined : ((json['bookings'] as Array<any>).map(EntitiesBookingFromJSON)),
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'endTime': json['end_time'] == null ? undefined : json['end_time'],
        'id': json['id'] == null ? undefined : json['id'],
        'maxAttendees': json['max_attendees'] == null ? undefined : json['max_attendees'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'status': json['status'] == null ? undefined : EntitiesAppointmentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'] == null ? undefined : EntitiesAppointmentTypeFromJSON(json['type']),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function EntitiesAppointmentToJSON(json: any): EntitiesAppointment {
    return EntitiesAppointmentToJSONTyped(json, false);
}

export function EntitiesAppointmentToJSONTyped(value?: EntitiesAppointment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'anti_scalping_level': EntitiesAntiScalpingLevelToJSON(value['antiScalpingLevel']),
        'app_code': value['appCode'],
        'attendees_booked': value['attendeesBooked'],
        'booking_duration': value['bookingDuration'],
        'bookings': value['bookings'] == null ? undefined : ((value['bookings'] as Array<any>).map(EntitiesBookingToJSON)),
        'created_at': value['createdAt'],
        'deleted_at': value['deletedAt'] == null ? value['deletedAt'] : value['deletedAt'].toISOString(),
        'description': value['description'],
        'end_date': value['endDate'],
        'end_time': value['endTime'],
        'id': value['id'],
        'max_attendees': value['maxAttendees'],
        'owner_id': value['ownerId'],
        'start_date': value['startDate'],
        'start_time': value['startTime'],
        'status': EntitiesAppointmentStatusToJSON(value['status']),
        'title': value['title'],
        'type': EntitiesAppointmentTypeToJSON(value['type']),
        'updated_at': value['updatedAt'],
    };
}

