/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorsFieldError } from './ErrorsFieldError';
import {
    ErrorsFieldErrorFromJSON,
    ErrorsFieldErrorFromJSONTyped,
    ErrorsFieldErrorToJSON,
    ErrorsFieldErrorToJSONTyped,
} from './ErrorsFieldError';

/**
 * 
 * @export
 * @interface ErrorsAPIErrorResponse
 */
export interface ErrorsAPIErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorsAPIErrorResponse
     */
    code?: string;
    /**
     * 
     * @type {Array<ErrorsFieldError>}
     * @memberof ErrorsAPIErrorResponse
     */
    fields?: Array<ErrorsFieldError>;
    /**
     * 
     * @type {string}
     * @memberof ErrorsAPIErrorResponse
     */
    message?: string;
    /**
     * 
     * @type {object}
     * @memberof ErrorsAPIErrorResponse
     */
    meta?: object;
    /**
     * 
     * @type {string}
     * @memberof ErrorsAPIErrorResponse
     */
    requestId?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorsAPIErrorResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the ErrorsAPIErrorResponse interface.
 */
export function instanceOfErrorsAPIErrorResponse(value: object): value is ErrorsAPIErrorResponse {
    return true;
}

export function ErrorsAPIErrorResponseFromJSON(json: any): ErrorsAPIErrorResponse {
    return ErrorsAPIErrorResponseFromJSONTyped(json, false);
}

export function ErrorsAPIErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorsAPIErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'fields': json['fields'] == null ? undefined : ((json['fields'] as Array<any>).map(ErrorsFieldErrorFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'meta': json['meta'] == null ? undefined : json['meta'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ErrorsAPIErrorResponseToJSON(json: any): ErrorsAPIErrorResponse {
    return ErrorsAPIErrorResponseToJSONTyped(json, false);
}

export function ErrorsAPIErrorResponseToJSONTyped(value?: ErrorsAPIErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'fields': value['fields'] == null ? undefined : ((value['fields'] as Array<any>).map(ErrorsFieldErrorToJSON)),
        'message': value['message'],
        'meta': value['meta'],
        'request_id': value['requestId'],
        'status': value['status'],
    };
}

