/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorsFieldError
 */
export interface ErrorsFieldError {
    /**
     * 
     * @type {string}
     * @memberof ErrorsFieldError
     */
    field?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorsFieldError
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorsFieldError
     */
    rule?: string;
}

/**
 * Check if a given object implements the ErrorsFieldError interface.
 */
export function instanceOfErrorsFieldError(value: object): value is ErrorsFieldError {
    return true;
}

export function ErrorsFieldErrorFromJSON(json: any): ErrorsFieldError {
    return ErrorsFieldErrorFromJSONTyped(json, false);
}

export function ErrorsFieldErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorsFieldError {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'message': json['message'] == null ? undefined : json['message'],
        'rule': json['rule'] == null ? undefined : json['rule'],
    };
}

export function ErrorsFieldErrorToJSON(json: any): ErrorsFieldError {
    return ErrorsFieldErrorToJSONTyped(json, false);
}

export function ErrorsFieldErrorToJSONTyped(value?: ErrorsFieldError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'message': value['message'],
        'rule': value['rule'],
    };
}

