/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesAppointmentResponse } from './ResponsesAppointmentResponse';
import {
    ResponsesAppointmentResponseFromJSON,
    ResponsesAppointmentResponseFromJSONTyped,
    ResponsesAppointmentResponseToJSON,
    ResponsesAppointmentResponseToJSONTyped,
} from './ResponsesAppointmentResponse';

/**
 * 
 * @export
 * @interface GetMyAppointments200Response
 */
export interface GetMyAppointments200Response {
    /**
     * 
     * @type {Array<ResponsesAppointmentResponse>}
     * @memberof GetMyAppointments200Response
     */
    items?: Array<ResponsesAppointmentResponse>;
    /**
     * 
     * @type {number}
     * @memberof GetMyAppointments200Response
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof GetMyAppointments200Response
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof GetMyAppointments200Response
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof GetMyAppointments200Response
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the GetMyAppointments200Response interface.
 */
export function instanceOfGetMyAppointments200Response(value: object): value is GetMyAppointments200Response {
    return true;
}

export function GetMyAppointments200ResponseFromJSON(json: any): GetMyAppointments200Response {
    return GetMyAppointments200ResponseFromJSONTyped(json, false);
}

export function GetMyAppointments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMyAppointments200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ResponsesAppointmentResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'total': json['total'] == null ? undefined : json['total'],
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
    };
}

export function GetMyAppointments200ResponseToJSON(json: any): GetMyAppointments200Response {
    return GetMyAppointments200ResponseToJSONTyped(json, false);
}

export function GetMyAppointments200ResponseToJSONTyped(value?: GetMyAppointments200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ResponsesAppointmentResponseToJSON)),
        'page': value['page'],
        'per_page': value['perPage'],
        'total': value['total'],
        'total_pages': value['totalPages'],
    };
}

