/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntitiesNotification } from './EntitiesNotification';
import {
    EntitiesNotificationFromJSON,
    EntitiesNotificationFromJSONTyped,
    EntitiesNotificationToJSON,
    EntitiesNotificationToJSONTyped,
} from './EntitiesNotification';

/**
 * 
 * @export
 * @interface GetNotifications200Response
 */
export interface GetNotifications200Response {
    /**
     * 
     * @type {Array<EntitiesNotification>}
     * @memberof GetNotifications200Response
     */
    items?: Array<EntitiesNotification>;
    /**
     * 
     * @type {number}
     * @memberof GetNotifications200Response
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof GetNotifications200Response
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof GetNotifications200Response
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof GetNotifications200Response
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the GetNotifications200Response interface.
 */
export function instanceOfGetNotifications200Response(value: object): value is GetNotifications200Response {
    return true;
}

export function GetNotifications200ResponseFromJSON(json: any): GetNotifications200Response {
    return GetNotifications200ResponseFromJSONTyped(json, false);
}

export function GetNotifications200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNotifications200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(EntitiesNotificationFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'total': json['total'] == null ? undefined : json['total'],
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
    };
}

export function GetNotifications200ResponseToJSON(json: any): GetNotifications200Response {
    return GetNotifications200ResponseToJSONTyped(json, false);
}

export function GetNotifications200ResponseToJSONTyped(value?: GetNotifications200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(EntitiesNotificationToJSON)),
        'page': value['page'],
        'per_page': value['perPage'],
        'total': value['total'],
        'total_pages': value['totalPages'],
    };
}

