/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestsBookingRequest
 */
export interface RequestsBookingRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsBookingRequest
     */
    appCode: string;
    /**
     * 
     * @type {number}
     * @memberof RequestsBookingRequest
     */
    attendeeCount?: number;
    /**
     * 
     * @type {string}
     * @memberof RequestsBookingRequest
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsBookingRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsBookingRequest
     */
    deviceToken?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsBookingRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsBookingRequest
     */
    endTime: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsBookingRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsBookingRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsBookingRequest
     */
    startTime: string;
}

/**
 * Check if a given object implements the RequestsBookingRequest interface.
 */
export function instanceOfRequestsBookingRequest(value: object): value is RequestsBookingRequest {
    if (!('appCode' in value) || value['appCode'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    return true;
}

export function RequestsBookingRequestFromJSON(json: any): RequestsBookingRequest {
    return RequestsBookingRequestFromJSONTyped(json, false);
}

export function RequestsBookingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsBookingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appCode': json['app_code'],
        'attendeeCount': json['attendee_count'] == null ? undefined : json['attendee_count'],
        'date': json['date'],
        'description': json['description'] == null ? undefined : json['description'],
        'deviceToken': json['device_token'] == null ? undefined : json['device_token'],
        'email': json['email'] == null ? undefined : json['email'],
        'endTime': json['end_time'],
        'name': json['name'] == null ? undefined : json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'startTime': json['start_time'],
    };
}

export function RequestsBookingRequestToJSON(json: any): RequestsBookingRequest {
    return RequestsBookingRequestToJSONTyped(json, false);
}

export function RequestsBookingRequestToJSONTyped(value?: RequestsBookingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_code': value['appCode'],
        'attendee_count': value['attendeeCount'],
        'date': value['date'],
        'description': value['description'],
        'device_token': value['deviceToken'],
        'email': value['email'],
        'end_time': value['endTime'],
        'name': value['name'],
        'phone': value['phone'],
        'start_time': value['startTime'],
    };
}

