/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestsRefreshTokenRequest
 */
export interface RequestsRefreshTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsRefreshTokenRequest
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the RequestsRefreshTokenRequest interface.
 */
export function instanceOfRequestsRefreshTokenRequest(value: object): value is RequestsRefreshTokenRequest {
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function RequestsRefreshTokenRequestFromJSON(json: any): RequestsRefreshTokenRequest {
    return RequestsRefreshTokenRequestFromJSONTyped(json, false);
}

export function RequestsRefreshTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsRefreshTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'],
    };
}

export function RequestsRefreshTokenRequestToJSON(json: any): RequestsRefreshTokenRequest {
    return RequestsRefreshTokenRequestToJSONTyped(json, false);
}

export function RequestsRefreshTokenRequestToJSONTyped(value?: RequestsRefreshTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refreshToken': value['refreshToken'],
    };
}

