/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestsDeviceTokenRequest
 */
export interface RequestsDeviceTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsDeviceTokenRequest
     */
    deviceId: string;
}

/**
 * Check if a given object implements the RequestsDeviceTokenRequest interface.
 */
export function instanceOfRequestsDeviceTokenRequest(value: object): value is RequestsDeviceTokenRequest {
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    return true;
}

export function RequestsDeviceTokenRequestFromJSON(json: any): RequestsDeviceTokenRequest {
    return RequestsDeviceTokenRequestFromJSONTyped(json, false);
}

export function RequestsDeviceTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsDeviceTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['device_id'],
    };
}

export function RequestsDeviceTokenRequestToJSON(json: any): RequestsDeviceTokenRequest {
    return RequestsDeviceTokenRequestToJSONTyped(json, false);
}

export function RequestsDeviceTokenRequestToJSONTyped(value?: RequestsDeviceTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device_id': value['deviceId'],
    };
}

