/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestsChangePasswordRequest
 */
export interface RequestsChangePasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsChangePasswordRequest
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsChangePasswordRequest
     */
    oldPassword: string;
}

/**
 * Check if a given object implements the RequestsChangePasswordRequest interface.
 */
export function instanceOfRequestsChangePasswordRequest(value: object): value is RequestsChangePasswordRequest {
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('oldPassword' in value) || value['oldPassword'] === undefined) return false;
    return true;
}

export function RequestsChangePasswordRequestFromJSON(json: any): RequestsChangePasswordRequest {
    return RequestsChangePasswordRequestFromJSONTyped(json, false);
}

export function RequestsChangePasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsChangePasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newPassword': json['new_password'],
        'oldPassword': json['old_password'],
    };
}

export function RequestsChangePasswordRequestToJSON(json: any): RequestsChangePasswordRequest {
    return RequestsChangePasswordRequestToJSONTyped(json, false);
}

export function RequestsChangePasswordRequestToJSONTyped(value?: RequestsChangePasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_password': value['newPassword'],
        'old_password': value['oldPassword'],
    };
}

