/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestsResendVerificationRequest
 */
export interface RequestsResendVerificationRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsResendVerificationRequest
     */
    email: string;
}

/**
 * Check if a given object implements the RequestsResendVerificationRequest interface.
 */
export function instanceOfRequestsResendVerificationRequest(value: object): value is RequestsResendVerificationRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function RequestsResendVerificationRequestFromJSON(json: any): RequestsResendVerificationRequest {
    return RequestsResendVerificationRequestFromJSONTyped(json, false);
}

export function RequestsResendVerificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsResendVerificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function RequestsResendVerificationRequestToJSON(json: any): RequestsResendVerificationRequest {
    return RequestsResendVerificationRequestToJSONTyped(json, false);
}

export function RequestsResendVerificationRequestToJSONTyped(value?: RequestsResendVerificationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

