/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestsForgotPasswordRequest
 */
export interface RequestsForgotPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsForgotPasswordRequest
     */
    email: string;
}

/**
 * Check if a given object implements the RequestsForgotPasswordRequest interface.
 */
export function instanceOfRequestsForgotPasswordRequest(value: object): value is RequestsForgotPasswordRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function RequestsForgotPasswordRequestFromJSON(json: any): RequestsForgotPasswordRequest {
    return RequestsForgotPasswordRequestFromJSONTyped(json, false);
}

export function RequestsForgotPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsForgotPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function RequestsForgotPasswordRequestToJSON(json: any): RequestsForgotPasswordRequest {
    return RequestsForgotPasswordRequestToJSONTyped(json, false);
}

export function RequestsForgotPasswordRequestToJSONTyped(value?: RequestsForgotPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

