/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestsBanRequest
 */
export interface RequestsBanRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsBanRequest
     */
    email: string;
}

/**
 * Check if a given object implements the RequestsBanRequest interface.
 */
export function instanceOfRequestsBanRequest(value: object): value is RequestsBanRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function RequestsBanRequestFromJSON(json: any): RequestsBanRequest {
    return RequestsBanRequestFromJSONTyped(json, false);
}

export function RequestsBanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsBanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function RequestsBanRequestToJSON(json: any): RequestsBanRequest {
    return RequestsBanRequestToJSONTyped(json, false);
}

export function RequestsBanRequestToJSONTyped(value?: RequestsBanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

