/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestsUserRequest
 */
export interface RequestsUserRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsUserRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsUserRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsUserRequest
     */
    password: string;
}

/**
 * Check if a given object implements the RequestsUserRequest interface.
 */
export function instanceOfRequestsUserRequest(value: object): value is RequestsUserRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RequestsUserRequestFromJSON(json: any): RequestsUserRequest {
    return RequestsUserRequestFromJSONTyped(json, false);
}

export function RequestsUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
        'password': json['password'],
    };
}

export function RequestsUserRequestToJSON(json: any): RequestsUserRequest {
    return RequestsUserRequestToJSONTyped(json, false);
}

export function RequestsUserRequestToJSONTyped(value?: RequestsUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'password': value['password'],
    };
}

