/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestsResetPasswordRequest
 */
export interface RequestsResetPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsResetPasswordRequest
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsResetPasswordRequest
     */
    token: string;
}

/**
 * Check if a given object implements the RequestsResetPasswordRequest interface.
 */
export function instanceOfRequestsResetPasswordRequest(value: object): value is RequestsResetPasswordRequest {
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function RequestsResetPasswordRequestFromJSON(json: any): RequestsResetPasswordRequest {
    return RequestsResetPasswordRequestFromJSONTyped(json, false);
}

export function RequestsResetPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsResetPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newPassword': json['new_password'],
        'token': json['token'],
    };
}

export function RequestsResetPasswordRequestToJSON(json: any): RequestsResetPasswordRequest {
    return RequestsResetPasswordRequestToJSONTyped(json, false);
}

export function RequestsResetPasswordRequestToJSONTyped(value?: RequestsResetPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_password': value['newPassword'],
        'token': value['token'],
    };
}

