/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesTimeSeriesPoint } from './ResponsesTimeSeriesPoint';
import {
    ResponsesTimeSeriesPointFromJSON,
    ResponsesTimeSeriesPointFromJSONTyped,
    ResponsesTimeSeriesPointToJSON,
    ResponsesTimeSeriesPointToJSONTyped,
} from './ResponsesTimeSeriesPoint';

/**
 * 
 * @export
 * @interface ResponsesDashboardAnalyticsResponse
 */
export interface ResponsesDashboardAnalyticsResponse {
    /**
     * 
     * @type {Array<ResponsesTimeSeriesPoint>}
     * @memberof ResponsesDashboardAnalyticsResponse
     */
    bookingsPerDay?: Array<ResponsesTimeSeriesPoint>;
    /**
     * 
     * @type {Array<ResponsesTimeSeriesPoint>}
     * @memberof ResponsesDashboardAnalyticsResponse
     */
    cancellationsPerDay?: Array<ResponsesTimeSeriesPoint>;
    /**
     * 
     * @type {string}
     * @memberof ResponsesDashboardAnalyticsResponse
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesDashboardAnalyticsResponse
     */
    startDate?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesDashboardAnalyticsResponse
     */
    totalAppointments?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsesDashboardAnalyticsResponse
     */
    totalBookings?: number;
}

/**
 * Check if a given object implements the ResponsesDashboardAnalyticsResponse interface.
 */
export function instanceOfResponsesDashboardAnalyticsResponse(value: object): value is ResponsesDashboardAnalyticsResponse {
    return true;
}

export function ResponsesDashboardAnalyticsResponseFromJSON(json: any): ResponsesDashboardAnalyticsResponse {
    return ResponsesDashboardAnalyticsResponseFromJSONTyped(json, false);
}

export function ResponsesDashboardAnalyticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesDashboardAnalyticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bookingsPerDay': json['bookings_per_day'] == null ? undefined : ((json['bookings_per_day'] as Array<any>).map(ResponsesTimeSeriesPointFromJSON)),
        'cancellationsPerDay': json['cancellations_per_day'] == null ? undefined : ((json['cancellations_per_day'] as Array<any>).map(ResponsesTimeSeriesPointFromJSON)),
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'totalAppointments': json['total_appointments'] == null ? undefined : json['total_appointments'],
        'totalBookings': json['total_bookings'] == null ? undefined : json['total_bookings'],
    };
}

export function ResponsesDashboardAnalyticsResponseToJSON(json: any): ResponsesDashboardAnalyticsResponse {
    return ResponsesDashboardAnalyticsResponseToJSONTyped(json, false);
}

export function ResponsesDashboardAnalyticsResponseToJSONTyped(value?: ResponsesDashboardAnalyticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookings_per_day': value['bookingsPerDay'] == null ? undefined : ((value['bookingsPerDay'] as Array<any>).map(ResponsesTimeSeriesPointToJSON)),
        'cancellations_per_day': value['cancellationsPerDay'] == null ? undefined : ((value['cancellationsPerDay'] as Array<any>).map(ResponsesTimeSeriesPointToJSON)),
        'end_date': value['endDate'],
        'start_date': value['startDate'],
        'total_appointments': value['totalAppointments'],
        'total_bookings': value['totalBookings'],
    };
}

