/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesAnalyticsResponsePartyCapacity
 */
export interface ResponsesAnalyticsResponsePartyCapacity {
    /**
     * 
     * @type {number}
     * @memberof ResponsesAnalyticsResponsePartyCapacity
     */
    percent?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsesAnalyticsResponsePartyCapacity
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsesAnalyticsResponsePartyCapacity
     */
    used?: number;
}

/**
 * Check if a given object implements the ResponsesAnalyticsResponsePartyCapacity interface.
 */
export function instanceOfResponsesAnalyticsResponsePartyCapacity(value: object): value is ResponsesAnalyticsResponsePartyCapacity {
    return true;
}

export function ResponsesAnalyticsResponsePartyCapacityFromJSON(json: any): ResponsesAnalyticsResponsePartyCapacity {
    return ResponsesAnalyticsResponsePartyCapacityFromJSONTyped(json, false);
}

export function ResponsesAnalyticsResponsePartyCapacityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesAnalyticsResponsePartyCapacity {
    if (json == null) {
        return json;
    }
    return {
        
        'percent': json['percent'] == null ? undefined : json['percent'],
        'total': json['total'] == null ? undefined : json['total'],
        'used': json['used'] == null ? undefined : json['used'],
    };
}

export function ResponsesAnalyticsResponsePartyCapacityToJSON(json: any): ResponsesAnalyticsResponsePartyCapacity {
    return ResponsesAnalyticsResponsePartyCapacityToJSONTyped(json, false);
}

export function ResponsesAnalyticsResponsePartyCapacityToJSONTyped(value?: ResponsesAnalyticsResponsePartyCapacity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'percent': value['percent'],
        'total': value['total'],
        'used': value['used'],
    };
}

