/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntitiesAppointmentType } from './EntitiesAppointmentType';
import {
    EntitiesAppointmentTypeFromJSON,
    EntitiesAppointmentTypeFromJSONTyped,
    EntitiesAppointmentTypeToJSON,
    EntitiesAppointmentTypeToJSONTyped,
} from './EntitiesAppointmentType';

/**
 * 
 * @export
 * @interface ResponsesAppointmentResponse
 */
export interface ResponsesAppointmentResponse {
    /**
     * 
     * @type {string}
     * @memberof ResponsesAppointmentResponse
     */
    appCode?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesAppointmentResponse
     */
    bookingDuration?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAppointmentResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAppointmentResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAppointmentResponse
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAppointmentResponse
     */
    endTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAppointmentResponse
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesAppointmentResponse
     */
    maxAttendees?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAppointmentResponse
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAppointmentResponse
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAppointmentResponse
     */
    title?: string;
    /**
     * 
     * @type {EntitiesAppointmentType}
     * @memberof ResponsesAppointmentResponse
     */
    type?: EntitiesAppointmentType;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAppointmentResponse
     */
    updatedAt?: string;
}



/**
 * Check if a given object implements the ResponsesAppointmentResponse interface.
 */
export function instanceOfResponsesAppointmentResponse(value: object): value is ResponsesAppointmentResponse {
    return true;
}

export function ResponsesAppointmentResponseFromJSON(json: any): ResponsesAppointmentResponse {
    return ResponsesAppointmentResponseFromJSONTyped(json, false);
}

export function ResponsesAppointmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesAppointmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appCode': json['app_code'] == null ? undefined : json['app_code'],
        'bookingDuration': json['booking_duration'] == null ? undefined : json['booking_duration'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'endTime': json['end_time'] == null ? undefined : json['end_time'],
        'id': json['id'] == null ? undefined : json['id'],
        'maxAttendees': json['max_attendees'] == null ? undefined : json['max_attendees'],
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'] == null ? undefined : EntitiesAppointmentTypeFromJSON(json['type']),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ResponsesAppointmentResponseToJSON(json: any): ResponsesAppointmentResponse {
    return ResponsesAppointmentResponseToJSONTyped(json, false);
}

export function ResponsesAppointmentResponseToJSONTyped(value?: ResponsesAppointmentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_code': value['appCode'],
        'booking_duration': value['bookingDuration'],
        'created_at': value['createdAt'],
        'description': value['description'],
        'end_date': value['endDate'],
        'end_time': value['endTime'],
        'id': value['id'],
        'max_attendees': value['maxAttendees'],
        'start_date': value['startDate'],
        'start_time': value['startTime'],
        'title': value['title'],
        'type': EntitiesAppointmentTypeToJSON(value['type']),
        'updated_at': value['updatedAt'],
    };
}

