/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesUserResponse
 */
export interface ResponsesUserResponse {
    /**
     * 
     * @type {string}
     * @memberof ResponsesUserResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesUserResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesUserResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesUserResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesUserResponse
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesUserResponse
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ResponsesUserResponse interface.
 */
export function instanceOfResponsesUserResponse(value: object): value is ResponsesUserResponse {
    return true;
}

export function ResponsesUserResponseFromJSON(json: any): ResponsesUserResponse {
    return ResponsesUserResponseFromJSONTyped(json, false);
}

export function ResponsesUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ResponsesUserResponseToJSON(json: any): ResponsesUserResponse {
    return ResponsesUserResponseToJSONTyped(json, false);
}

export function ResponsesUserResponseToJSONTyped(value?: ResponsesUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'email': value['email'],
        'id': value['id'],
        'name': value['name'],
        'phone_number': value['phoneNumber'],
        'updated_at': value['updatedAt'],
    };
}

