/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesAPIErrorResponse
 */
export interface ResponsesAPIErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ResponsesAPIErrorResponse
     */
    code?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesAPIErrorResponse
     */
    http?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAPIErrorResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the ResponsesAPIErrorResponse interface.
 */
export function instanceOfResponsesAPIErrorResponse(value: object): value is ResponsesAPIErrorResponse {
    return true;
}

export function ResponsesAPIErrorResponseFromJSON(json: any): ResponsesAPIErrorResponse {
    return ResponsesAPIErrorResponseFromJSONTyped(json, false);
}

export function ResponsesAPIErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesAPIErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'http': json['http'] == null ? undefined : json['http'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ResponsesAPIErrorResponseToJSON(json: any): ResponsesAPIErrorResponse {
    return ResponsesAPIErrorResponseToJSONTyped(json, false);
}

export function ResponsesAPIErrorResponseToJSONTyped(value?: ResponsesAPIErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'http': value['http'],
        'message': value['message'],
    };
}

