/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesTokenResponse
 */
export interface ResponsesTokenResponse {
    /**
     * 
     * @type {number}
     * @memberof ResponsesTokenResponse
     */
    expiresIn?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponsesTokenResponse
     */
    refreshToken?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesTokenResponse
     */
    token?: string;
}

/**
 * Check if a given object implements the ResponsesTokenResponse interface.
 */
export function instanceOfResponsesTokenResponse(value: object): value is ResponsesTokenResponse {
    return true;
}

export function ResponsesTokenResponseFromJSON(json: any): ResponsesTokenResponse {
    return ResponsesTokenResponseFromJSONTyped(json, false);
}

export function ResponsesTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function ResponsesTokenResponseToJSON(json: any): ResponsesTokenResponse {
    return ResponsesTokenResponseToJSONTyped(json, false);
}

export function ResponsesTokenResponseToJSONTyped(value?: ResponsesTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires_in': value['expiresIn'],
        'refresh_token': value['refreshToken'],
        'token': value['token'],
    };
}

