/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesTimeSeriesPoint
 */
export interface ResponsesTimeSeriesPoint {
    /**
     * 
     * @type {number}
     * @memberof ResponsesTimeSeriesPoint
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponsesTimeSeriesPoint
     */
    date?: string;
}

/**
 * Check if a given object implements the ResponsesTimeSeriesPoint interface.
 */
export function instanceOfResponsesTimeSeriesPoint(value: object): value is ResponsesTimeSeriesPoint {
    return true;
}

export function ResponsesTimeSeriesPointFromJSON(json: any): ResponsesTimeSeriesPoint {
    return ResponsesTimeSeriesPointFromJSONTyped(json, false);
}

export function ResponsesTimeSeriesPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesTimeSeriesPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'date': json['date'] == null ? undefined : json['date'],
    };
}

export function ResponsesTimeSeriesPointToJSON(json: any): ResponsesTimeSeriesPoint {
    return ResponsesTimeSeriesPointToJSONTyped(json, false);
}

export function ResponsesTimeSeriesPointToJSONTyped(value?: ResponsesTimeSeriesPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'date': value['date'],
    };
}

