/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesTimeSeriesPoint } from './ResponsesTimeSeriesPoint';
import {
    ResponsesTimeSeriesPointFromJSON,
    ResponsesTimeSeriesPointFromJSONTyped,
    ResponsesTimeSeriesPointToJSON,
    ResponsesTimeSeriesPointToJSONTyped,
} from './ResponsesTimeSeriesPoint';

/**
 * 
 * @export
 * @interface ResponsesAnalyticsResponse
 */
export interface ResponsesAnalyticsResponse {
    /**
     * derived from total bookings / days in range
     * @type {number}
     * @memberof ResponsesAnalyticsResponse
     */
    avgBookingsPerDay?: number;
    /**
     * Time series
     * @type {Array<ResponsesTimeSeriesPoint>}
     * @memberof ResponsesAnalyticsResponse
     */
    bookingsPerDay?: Array<ResponsesTimeSeriesPoint>;
    /**
     * percent 0-100
     * @type {number}
     * @memberof ResponsesAnalyticsResponse
     */
    cancellationRate?: number;
    /**
     * 
     * @type {Array<ResponsesTimeSeriesPoint>}
     * @memberof ResponsesAnalyticsResponse
     */
    cancellationsPerDay?: Array<ResponsesTimeSeriesPoint>;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAnalyticsResponse
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesAnalyticsResponse
     */
    startDate?: string;
    /**
     * Summary
     * @type {number}
     * @memberof ResponsesAnalyticsResponse
     */
    totalAppointments?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsesAnalyticsResponse
     */
    totalBookings?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsesAnalyticsResponse
     */
    totalCancellations?: number;
}

/**
 * Check if a given object implements the ResponsesAnalyticsResponse interface.
 */
export function instanceOfResponsesAnalyticsResponse(value: object): value is ResponsesAnalyticsResponse {
    return true;
}

export function ResponsesAnalyticsResponseFromJSON(json: any): ResponsesAnalyticsResponse {
    return ResponsesAnalyticsResponseFromJSONTyped(json, false);
}

export function ResponsesAnalyticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesAnalyticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'avgBookingsPerDay': json['avg_bookings_per_day'] == null ? undefined : json['avg_bookings_per_day'],
        'bookingsPerDay': json['bookings_per_day'] == null ? undefined : ((json['bookings_per_day'] as Array<any>).map(ResponsesTimeSeriesPointFromJSON)),
        'cancellationRate': json['cancellation_rate'] == null ? undefined : json['cancellation_rate'],
        'cancellationsPerDay': json['cancellations_per_day'] == null ? undefined : ((json['cancellations_per_day'] as Array<any>).map(ResponsesTimeSeriesPointFromJSON)),
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'totalAppointments': json['total_appointments'] == null ? undefined : json['total_appointments'],
        'totalBookings': json['total_bookings'] == null ? undefined : json['total_bookings'],
        'totalCancellations': json['total_cancellations'] == null ? undefined : json['total_cancellations'],
    };
}

export function ResponsesAnalyticsResponseToJSON(json: any): ResponsesAnalyticsResponse {
    return ResponsesAnalyticsResponseToJSONTyped(json, false);
}

export function ResponsesAnalyticsResponseToJSONTyped(value?: ResponsesAnalyticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avg_bookings_per_day': value['avgBookingsPerDay'],
        'bookings_per_day': value['bookingsPerDay'] == null ? undefined : ((value['bookingsPerDay'] as Array<any>).map(ResponsesTimeSeriesPointToJSON)),
        'cancellation_rate': value['cancellationRate'],
        'cancellations_per_day': value['cancellationsPerDay'] == null ? undefined : ((value['cancellationsPerDay'] as Array<any>).map(ResponsesTimeSeriesPointToJSON)),
        'end_date': value['endDate'],
        'start_date': value['startDate'],
        'total_appointments': value['totalAppointments'],
        'total_bookings': value['totalBookings'],
        'total_cancellations': value['totalCancellations'],
    };
}

