/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesSimpleMessage
 */
export interface ResponsesSimpleMessage {
    /**
     * 
     * @type {object}
     * @memberof ResponsesSimpleMessage
     */
    data?: object;
    /**
     * 
     * @type {string}
     * @memberof ResponsesSimpleMessage
     */
    message?: string;
}

/**
 * Check if a given object implements the ResponsesSimpleMessage interface.
 */
export function instanceOfResponsesSimpleMessage(value: object): value is ResponsesSimpleMessage {
    return true;
}

export function ResponsesSimpleMessageFromJSON(json: any): ResponsesSimpleMessage {
    return ResponsesSimpleMessageFromJSONTyped(json, false);
}

export function ResponsesSimpleMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesSimpleMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ResponsesSimpleMessageToJSON(json: any): ResponsesSimpleMessage {
    return ResponsesSimpleMessageToJSONTyped(json, false);
}

export function ResponsesSimpleMessageToJSONTyped(value?: ResponsesSimpleMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'message': value['message'],
    };
}

