/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesTopAppointment
 */
export interface ResponsesTopAppointment {
    /**
     * 
     * @type {string}
     * @memberof ResponsesTopAppointment
     */
    appCode?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesTopAppointment
     */
    bookings?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponsesTopAppointment
     */
    capacityUsagePercent?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponsesTopAppointment
     */
    title?: string;
}

/**
 * Check if a given object implements the ResponsesTopAppointment interface.
 */
export function instanceOfResponsesTopAppointment(value: object): value is ResponsesTopAppointment {
    return true;
}

export function ResponsesTopAppointmentFromJSON(json: any): ResponsesTopAppointment {
    return ResponsesTopAppointmentFromJSONTyped(json, false);
}

export function ResponsesTopAppointmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesTopAppointment {
    if (json == null) {
        return json;
    }
    return {
        
        'appCode': json['app_code'] == null ? undefined : json['app_code'],
        'bookings': json['bookings'] == null ? undefined : json['bookings'],
        'capacityUsagePercent': json['capacity_usage_percent'] == null ? undefined : json['capacity_usage_percent'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function ResponsesTopAppointmentToJSON(json: any): ResponsesTopAppointment {
    return ResponsesTopAppointmentToJSONTyped(json, false);
}

export function ResponsesTopAppointmentToJSONTyped(value?: ResponsesTopAppointment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_code': value['appCode'],
        'bookings': value['bookings'],
        'capacity_usage_percent': value['capacityUsagePercent'],
        'title': value['title'],
    };
}

