/* tslint:disable */
/* eslint-disable */
/**
 * Asiko API
 * This is a comprehensive API for creating and managing appointments.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesUserResponse } from './ResponsesUserResponse';
import {
    ResponsesUserResponseFromJSON,
    ResponsesUserResponseFromJSONTyped,
    ResponsesUserResponseToJSON,
    ResponsesUserResponseToJSONTyped,
} from './ResponsesUserResponse';

/**
 * 
 * @export
 * @interface ResponsesLoginResponse
 */
export interface ResponsesLoginResponse {
    /**
     * 
     * @type {number}
     * @memberof ResponsesLoginResponse
     */
    expiresIn?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponsesLoginResponse
     */
    refreshToken?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesLoginResponse
     */
    token?: string;
    /**
     * 
     * @type {ResponsesUserResponse}
     * @memberof ResponsesLoginResponse
     */
    user?: ResponsesUserResponse;
}

/**
 * Check if a given object implements the ResponsesLoginResponse interface.
 */
export function instanceOfResponsesLoginResponse(value: object): value is ResponsesLoginResponse {
    return true;
}

export function ResponsesLoginResponseFromJSON(json: any): ResponsesLoginResponse {
    return ResponsesLoginResponseFromJSONTyped(json, false);
}

export function ResponsesLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'token': json['token'] == null ? undefined : json['token'],
        'user': json['user'] == null ? undefined : ResponsesUserResponseFromJSON(json['user']),
    };
}

export function ResponsesLoginResponseToJSON(json: any): ResponsesLoginResponse {
    return ResponsesLoginResponseToJSONTyped(json, false);
}

export function ResponsesLoginResponseToJSONTyped(value?: ResponsesLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires_in': value['expiresIn'],
        'refresh_token': value['refreshToken'],
        'token': value['token'],
        'user': ResponsesUserResponseToJSON(value['user']),
    };
}

